### ISSUE TITLE
dragNodes: move multiple nodes

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#1]
After activating multiple nodes (see `sigma.plugins.activeState`), we should be able to drag them at once. This would require a complete rewrite of the dragNodes plugin.

* 1 node should be draggable without activating it
* multiple active nodes should be draggable

Dragging may occur by mouse events or touch events.

The plugin should handle multiple sigma instances (only one instance is handled now).
The plugin should allow to bind functions to its events, thus extending `sigma.classes.dispatcher`.

The plugin should be compatible only with the `canvas` renderer, as it is currently the case.

Existing plugin: https://github.com/Linkurious/sigma.js/tree/linkurious-version/plugins/sigma.plugins.dragNodes

**Comment by partizanos** [comment]
Hello can you post as example the combiation of lasso to select them all and drag.nodes plugin?
I saw a gif demonstrating this functionality.

**Comment by sheymann** [comment]
@partizanos sure, I've planned to add it to the wiki FAQ :)

**Comment by sheymann** [comment]
@partizanos see https://github.com/Linkurious/linkurious.js/wiki/How-to-select-and-drag-multiple-nodes

Let me know what you think about it!

**Comment by partizanos** [comment]
Awesome! Thank you dude!

On Tue, Mar 10, 2015 at 3:45 PM, Sébastien Heymann <notifications@github.com
> wrote:

> @partizanos <https://github.com/partizanos> see
> https://github.com/Linkurious/linkurious.js/wiki/How-to-select-and-drag-multiple-nodes
>
> Let me know what you think about it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Linkurious/linkurious.js/issues/1#issuecomment-78068109>
> .
>



-- 
Dimitris Proios
Undergraduate Student,
Dept Informatics and Telematics,
Harokopio University

**Comment by partizanos** [comment]
I will provide some feedback tomorrow, but really thanks a lot!

On Tue, Mar 10, 2015 at 6:02 PM, dimitris proios <dimi.proios@gmail.com>
wrote:

> Awesome! Thank you dude!
>
> On Tue, Mar 10, 2015 at 3:45 PM, Sébastien Heymann <
> notifications@github.com> wrote:
>
>> @partizanos <https://github.com/partizanos> see
>> https://github.com/Linkurious/linkurious.js/wiki/How-to-select-and-drag-multiple-nodes
>>
>> Let me know what you think about it!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Linkurious/linkurious.js/issues/1#issuecomment-78068109>
>> .
>>
>
>
>
> --
> Dimitris Proios
> Undergraduate Student,
> Dept Informatics and Telematics,
> Harokopio University
>



-- 
Dimitris Proios
Undergraduate Student,
Dept Informatics and Telematics,
Harokopio University

**Comment by sheymann** [comment]
Hey @partizanos how was it so far?

**Comment by partizanos** [comment]
Hey dude it works fine I am trying to embed it to my main system. Still
have some conflicts with the merge but it does exactly what I want. I also
modified it in a way that it gets active/dead by key shortcut and change
color when a ndoe is selected. But great work in general :)

On Fri, Mar 20, 2015 at 3:16 PM, Sébastien Heymann <notifications@github.com
> wrote:

> Hey @partizanos <https://github.com/partizanos> how was it so far?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Linkurious/linkurious.js/issues/1#issuecomment-84026634>
> .
>



-- 
Dimitris Proios
Undergraduate Student,
Dept Informatics and Telematics,
Harokopio University
