### ISSUE TITLE
Cursor does not revert after deactivating lasso plugin

### ISSUE THREAD

**Issue by apitts** [Linkurious/linkurious.js#101]
To replicate: toggle the lasso plugin on and then toggle off without moving the mouse and while using Chrome.  On toggling lasso on the cursor changes (to for example crosshair if so chosen).  However, on toggling lasso off the cursor does not change until the mouse is moved.  

I believe this is a known issue with Chrome: 
https://code.google.com/p/chromium/issues/detail?id=26723

I have experimented with the fix suggested in the above, i.e.:
```
function setCursor(cursor) {
        if (document.body.style.cursor != cursor) {
            var wkch = document.createElement("div");
            wkch.style.overflow = "hidden";
            wkch.style.position = "absolute";
            wkch.style.left = "0px";
            wkch.style.top = "0px";
            wkch.style.width = "100%";
            wkch.style.height = "100%";
            var wkch2 = document.createElement("div");
            wkch2.style.width = "200%";
            wkch2.style.height = "200%";
            wkch.appendChild(wkch2);
            document.body.appendChild(wkch);
            document.body.style.cursor = cursor;
            wkch.scrollLeft = 1;
            wkch.scrollLeft = 0;
            document.body.removeChild(wkch);
        }
    }

The above worked initially but, after I upgraded my Chrome version it stopped working so seems to be somewhat fragile.

Would be great to know if anyone else has experienced this issue.

**Comment by sheymann** [comment]
I confirm the bug but I've not come with any good solution. As it's a Chrome issue I suggest to ignore it.

**Comment by apitts** [comment]
Thanks!  I find it very annoying..I will be sure to comment on this issue if I find a good solution.  Closing the issue for the moment.
