### ISSUE TITLE
how to show label on edge only from specific zooming 

### ISSUE THREAD

**Issue by ellavs1** [Linkurious/linkurious.js#103]
I would like to show labels on edge only when the user zoom in

**Comment by sheymann** [comment]
Hello, you need to use the plugin [sigma.renderers.edgeLabels](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.renderers.edgeLabels). Then set the sigma setting `edgeLabelThreshold` with the minimum size the edges should have to get their label displayed.

**Comment by sheymann** [comment]
@ellavs1 does it solve your issue?
