### ISSUE TITLE
Switching Back and Forth between Nodes on Hover

### ISSUE THREAD

**Issue by mangowebdesign** [Linkurious/linkurious.js#118]
I have a very large graph that uses ForceAtlas. At a zoom level where it is zoomed out, the nodes appear on top of each other. What is happening is that if I hover over a node, the node switches between the hovered and the other node it is on top of (my overNode function creates a halo around itself and the node's neighbors). It will continuously switch between the two nodes at a very fast rate. Can I maybe bring the z-index of a particular node up to prevent this (if possible)? Or is there another method? Thanks. 
![screen shot 2015-06-04 at 4 56 07 pm](https://cloud.githubusercontent.com/assets/6474505/7994339/9f4f4f28-0ada-11e5-9814-57e285971e06.png)
![node1](https://cloud.githubusercontent.com/assets/6474505/7994377/0492106e-0adb-11e5-9c81-ae397e55ec84.png)
![node2](https://cloud.githubusercontent.com/assets/6474505/7994378/0495b41c-0adb-11e5-85c9-b5bb34e40854.png)

**Comment by sheymann** [comment]
It's not possible to set a z-index kind of property, however you can:

- decrease the Sigma setting `nodesPowRatio` to reduce the size of the nodes when zoomed out so that they have a lower probability to overlap,
- set the Sigma setting `singleHover` to true, to force at most a single node to be hovered.

**Comment by sheymann** [comment]
@mangowebdesign does it answer your question?

**Comment by mangowebdesign** [comment]
Unfortunately not. Instead I wrote a function to display the nodes in a checkered display to make sure there is ample room to separate. (~2000 nodes were used).

```javascript
    var n = finalNodes.length;
    var total_rows = 200;
    var count_per_row = n / total_rows;

    for (i=0; i < n; i++) {
    	var calcCoord = i / count_per_row;
    	var calcX = (calcCoord % 1) * vizWidth;
    	var calcY = (vizHeight / (total_rows - 1)) * Math.floor(calcCoord);

    	g.nodes.push({
			id: 'n' + finalNodes[i].id,
			label: finalNodes[i].title,
			x: calcX,
			y: calcY,
			size: sizeNodes,
			color: 'default',
			the_image: jsons.nodes[i].image
		});
    }
```
