### ISSUE TITLE
Suggestion/Request: Add a zoom controller

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#119]
One of the more frustrating issues I've run across in the graphs is the sensitivity of the mouse scroll zoom and the inability to reset the zoom back to original setting when the zoom is accidentally triggered while trying to scroll the page.

I would love to see a zoom controller (similar to google maps) built into the graphs somehow as a setting that can be enabled/disabled as well as enabling/disabling the zoom.

**Comment by sheymann** [comment]
Hi, you can integrate a zoomIn and and a zoomOut function to your own user interface:

```js
var zoomIn = function() {
  sigma.utils.zoomTo(
      _sigmaInstance.camera,
      0,
      0,
      1 / sigmaInstance.settings('zoomingRatio'),
      { duration: 300 }
    );
};
```

```js
var zoomOut = function() {
  sigma.utils.zoomTo(
      sigmaInstance.camera,
      0,
      0,
      sigmaInstance.settings('zoomingRatio'),
      { duration: 300 }
    );
};
```

```js
var zoomCenter = function() {
  sigma.utils.zoomTo(
      sigmaInstance.camera,
      0,
      0,
      1,
      { duration: 300 }
    );
};
```

Set the Sigma setting `zoomingRatio` to control the zoom sensitivity.

Set the Sigma setting `mouseWheelEnabled` to false to disable the zoom with the mouse.

See all settings here: https://github.com/Linkurious/linkurious.js/wiki/Settings

**Comment by emergingdzns** [comment]
Thanks! That was fairly easy, although I’m having trouble figuring out how to reset the graph back to original position and zoom.

Would greatly appreciate any pointers on this. The zoom in/out works great, but if the user pans and zooms out but don’t get to the right level, it could be very confusing.

I tried the zoomCenter function but it doesn’t seem to do anything. I changed the 1 in the zoom setting line to different numbers and it does trigger, but of course it doesn’t zoom right. So something about using just “1” isn’t working.

If there is a function for just resetting the graph back to the original, that would be helpful too, although it would be nice not to lose any other customizations made post the initial render.

Thank you again!

**Comment by sheymann** [comment]
Ah my mistake, this is a tricky one because the third parameter of `zoomTo` is like a zoom *step*.

You can use [`sigma.plugins.locate`](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.plugins.locate) with the method `locate.center()` to reset the zoom ratio and to center the camera. Alternatively, you can use `locate.nodes(['n0', 'n1', ...]);` to center the camera on a set of nodes (it could be all the nodes).

cheers

**Comment by emergingdzns** [comment]
I was able to add a simple bootstrap button group (using fontawesome icons) for a zoom controller. Just in case it helps anyone, here's the basic code:
html:
```
<div class="btn-group" role="group" aria-label="zoomController" style="margin-right: 40px;">
    <button type="button" class="btn btn-default" id="zoomOut" title="Zoom Out"><i class="fa fa-search-minus"></i></button>
    <button type="button" class="btn btn-default" id="zoomReset" title="Zoom Reset"><i class="fa fa-compass"></i></button>
    <button type="button" class="btn btn-default" id="zoomIn" title="Zoom In"><i class="fa fa-search-plus"></i></button>
</div>
```
Javascript:
```
s = new sigma({ ... }); // the usual stuff to create a graph
var zoomOut = function() {
  sigma.utils.zoomTo(
      s.camera,
      0,
      0,
      1 / s.settings('zoomingRatio'),
      { duration: 300 }
    );
};
var zoomIn = function() {
  sigma.utils.zoomTo(
      s.camera,
      0,
      0,
      s.settings('zoomingRatio'),
      { duration: 300 }
    );
};
var zoomCenter = function() {
  var loc = sigma.plugins.locate(s);
  loc.center(1);
};

$(document).ready(function() {
  $('#zoomIn').on('click',function(e) {
    e.preventDefault();
    zoomIn();
  });
  $('#zoomOut').on('click',function(e) {
    e.preventDefault();
    zoomOut();
  });
  $('#zoomReset').on('click',function(e) {
    e.preventDefault();
    zoomCenter();
  });
});
```

Hope it helps others.

**Comment by sheymann** [comment]
:+1:
