### ISSUE TITLE
exports.svg: missing edge labels

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#131]
sigma.svg.edges is missing an edge renderer.

**Comment by jvilledieu** [comment]
Not just in the svg export btw (I've never seen the relationship labels in the Excel export)

**Comment by sheymann** [comment]
@jvilledieu Not relevant: relationships labels in Linkurious are picked from the properties, which are exported.

**Comment by Ytawo** [comment]
I'm not sure about what you want here:
* does it concern the export only or the whole svg renderer?
* even in the canvas renderer I don't see where the drawing of edges' labels is done (no src/renderers/canvas/edgeLabel.def for example)

**Comment by sheymann** [comment]
It is missing in svg export because there is no svg renderer. Currently the edge labels are handled by the plugin sigma.renderers.edgeLabels

We should add sigma.svg.edges.labels.def.js (+curve and curvedArrow) inside this plugin if possible.

**Comment by Ytawo** [comment]
I don't get how I am supposed to do so my method is called automatically to display the edges.
Based on what I've seen, I tried to do the same:

**Comment by sheymann** [comment]
`src/renderers/sigma.renderers.svg.js` needs improvements
