### ISSUE TITLE
dots in the middle of my icon?

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#140]
I'm pulling data from Neo4j and displaying circles with an icon in the middle for each node.  however, in the middle of my circle appears a black dot.  I've reviewed the code carefully and I don't see how it deviates from the example plugin-customShapes-icons, which doesn't exhibit the problem.  

my code is here: http://pastebin.com/Fpm1f5p4 - can anyone point out what the issue is?

**Comment by sheymann** [comment]
Hello, the customShapes plugin is a sort of legacy plugin. I recommend to use [renderers.linkurious](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.renderers.linkurious) instead, which also provides different shapes.

Let me know if it helps.

**Comment by ekkis** [comment]
yes, much better thank you
