### ISSUE TITLE
Easy inclusions

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#141]
currently, my code has some 50 script inclusions.  mostly these come from examples I've been toying with, and I can see that they come in groups e.g. there are canvas rendering scripts and webgl rendering scripts.  I presume some of these includes are required for any application and would be considered core e.g. conrad.js, sigma.utils.js, etc.

I'd like to suggest that a module manager be included in the sigma core (so perhaps I'm posting in the wrong place?) that would allow something like:

```
<script src="../src/sigma.core.js"></script>
<script type="text/javascript">
    sigma.core.include('renderers/webgl', 'misc/animation');
    sigma.core.include('captors');
</script>
```

which would allow for a cleaner way of including required functionality.  this would allow bundles to be loaded together but still allow single files to be included

**Comment by sheymann** [comment]
You can run `grunt build` to minify the core and each plugins in a single file, and in seperated files. Edit the plugins list in [Gruntfile.js](https://github.com/Linkurious/linkurious.js/blob/linkurious-version/Gruntfile.js#L71) to remove the unwanted plugins
