### ISSUE TITLE
s.camera[0].goTo({....              does not work ok when adding more than 100 nodes to existing graph and using force atlas

### ISSUE THREAD

**Issue by ellavs1** [Linkurious/linkurious.js#144]
I create a new graph using force atlas2

I stop force atlas and kill force atlas

when the user do "double click" on a node , I get all node's neighbors and call force atlas again with configForceAtlas

after 6000 millseconds I stop force atlas and I would like to zoomIn to the double clicked node with the new neighbors.

It works fine when the node does not have so many neighbors but when it has , for example 300 neighbors , the  zoomIn is not good. it does not zoom to the double clicked node.

s.cameras[0].goTo({x:node['read_cam0:x'],
y:node['read_cam0:y'],
angle:0,
ratio:0.5}

**Comment by sheymann** [comment]
Hi, can you provide the complete source code? I'm sorry but your description is very confusing.

**Comment by sheymann** [comment]
@ellavs1 did you solve your issue?
