### ISSUE TITLE
Initial layout - choices

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#147]
when using the web server built into Neo4j, graphs open with all the nodes in the query.  as these do not fit in the viewport, it is possible to pan around the canvas.  I guess the rendering algorithm seeks to keep a certain distance between nodes that is pleasing to the eye.

in using the neo plugin for linkurious, the graph rendered contains all the nodes positioned within the viewport, such that they overlay each other and it's all big mess.  is there are ready-made solution for a display that is closer to the Neo built-in?

alternatively, are there algorithms out there that are smarter in laying stuff out?

**Comment by sheymann** [comment]
The issue is more likely to be related to the camera, but  there are many [settings](https://github.com/Linkurious/linkurious.js/wiki/Settings) at stake here: `autoRescale`, `nodesPowRatio`, `minNodeSize`, `maxNodeSize`...

[sigma.plugins.locate](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.plugins.locate) may help to focus the camera after the layout.

Do you have a screenshot?

**Comment by ekkis** [comment]
<img width="931" alt="2015-07-04 11 10 39 am" src="https://cloud.githubusercontent.com/assets/274980/8508974/84cc0194-223d-11e5-8474-a8c1af1ee0e8.png">

**Comment by ekkis** [comment]
something else that's been puzzling me is that not all the icons in font-awesome show up.  as you can see, there are yellow nodes that should have a little graph (\uF201) but for some reason it won't show up (I'm using the version of the font that's used by the examples in the linkurious package, but I also tried a direct reference to the CDN version, in which case it was worse, I got little squares instead of the expected icons)

**Comment by ekkis** [comment]
ok, I've figured out that the job of laying out the nodes is done by the `cypher_parse` method of the neo plugin, and its idiosyncrasy is to rather unimaginatively assign random values to the x and y coordinates.

the graph generation built into the Neo server does a much better job.  in thinking about it, an algorithm to lay stuff out better could work like this:

1) select the first node in the graph and position it at (0,0)
2) select all directly related nodes and position them a {minimum distance} away from the parent node
3) if any two siblings are closer than {minimum distance}, increase the distance from the parent until the siblings can be sufficiently separated
4) for each sibling perform steps 2 & 3 above

is there anything out there I could use so I don't have to write everything from scratch?

**Comment by sheymann** [comment]
How about applying one of the available layouts? https://github.com/Linkurious/linkurious.js/wiki/Layouts

**Comment by ekkis** [comment]
ok.  my original statement/problem:

> in using the neo plugin for linkurious, the graph rendered contains all the nodes positioned within the 
> viewport, such that they overlay each other and it's all big mess

and what I found after much frustration is that sigma settings allow a `scalingMode` which may be set to *outside* - this causes for nodes to be rendered outside the viewport, which relieves the cramming.  the layout's not great, it's still a big mess but at least it isn't all crammed into the viewport.

so that answers my question.

now onto other frustrations with this library (see issue with edge labels not showing up)

**Comment by sheymann** [comment]
Maybe you'd need a proper support from us instead of loosing so much time?
