### ISSUE TITLE
How to get edges back?

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#149]
passing `match (n) return n limit 100` to `sigma.neo4j.cyper()` doesn't seem to come back with edges, however, `match (n)-[r]-() return n, r limit 100` does.

is that because of the limit?  I'm accustomed to issuing the first form in the Neo4j built-in client and having it come back with nodes and edges, or is it a peculiarity of the plugin?

**Comment by sheymann** [comment]
Hi, `match (n) return n` does not return edges because the query does not return edges. 

The Neo4j browser is doing a second query to get edges between those nodes, but if you stick to the query language you should run `match (n)-[r]-() return n, r` to get nodes and edges.
