### ISSUE TITLE
Leaflet integration for geospatial

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#150]
## Issue

- nodes may have geographical coordinates (lat, long) to be positionned on a map
- map background may be provided by different sources using various technologies (svg, tiles)
- maps may contain additional elements and specific user interactions

## Proposal

- don't reinvent the wheel, [Leaflet](http://leafletjs.com/) is a good middleware
- should we add Linkurious.js as a Leaflet overlay called Leaflet.LinkuriousOverlay or find another way to have the map on background?
- maybe create a leaflet plugin, e.g. [Leaflet.D3SvgOverlay](https://github.com/teralytics/Leaflet.D3SvgOverlay)
- sync zoom events
- nodes data must have latitude and longitude coordinates
- ignore x,y if lat,long coords are available when loading nodes
- updating nodes lat,long coordinates should update their x,y coords
- need functions `latLngToLayerPoint` and `layerPointToLatLng` to map cartesian coords and geo coords

**Event flow:** leaflet-> events (zoom, pan, click) -> sigma

If we don't create an overlay:
- sigma container and leaflet container should overlap on the same position on the page and have the same width and height.
- sigma is on top of leaflet
- **Event flow:** sigma -> events (zoom, pan, click) -> leaflet
- set map position on leaflet using http://leafletjs.com/reference.html#map-setview

:warning: Leaflet has discrete zoom levels: 1, 2, 3, etc.. to serve corresponding tiles, but Sigma has continuous zoom levels

**EDIT: we don't create an overlay.**

- [x] animate node coordinates on enable/disable
- [x] update node geo coordinates on node drag
- [x] can revert node geo coordinates after drag
- [x] compatibility with plugins.locate
- outline nodes to spot them easily -> app responsibility
- take screenshot? https://github.com/mapbox/leaflet-image, need sync with sigma.exporters.image, free with Stamen basemaps (http://bl.ocks.org/jieter/7428399)
- [x] Emit 'enabled' events after nodes are sync
- [x] Emit 'disabled' events after node positions are restored
- [x] compatible with plugins.fullscreen
-  compatibility with plugins.keyboard -> fail, too many bugs

Idea: add a cartesian area to position nodes with no geo coordinates (optional, default: hide those nodes) -> need for a "static" node property for the camera not to manage those node coordinates

**Comment by sheymann** [comment]
User latitude/longitude as reference?

**Comment by sheymann** [comment]
Alternative to Leaflet: http://openlayers.org/

**Comment by sheymann** [comment]
good considerations: http://www.acuriousanimal.com/2013/05/05/the-problem-with-openlayers.html

**Comment by sheymann** [comment]
https://github.com/Linkurious/linkurious.js/tree/feature/leaflet-integration \o/

**Comment by jbilcke** [comment]
nice :)

**Comment by mringel** [comment]
This looks like exactly what I was looking for!  Is there a live demo of it anywhere?

**Comment by sheymann** [comment]
It's still a work-in-progress and I want to polish it before publishing.

A basic example is available here: https://github.com/Linkurious/linkurious.js/blob/feature/leaflet-integration/examples/plugin-leaflet.html

**Comment by sheymann** [comment]
TODO:
- animate node coordinates
- update node geo coordinates on node drag
