### ISSUE TITLE
Add 'beforeRender' event

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#152]
In the render function, there is a `render` event. I would like to add a beforeRender event.

It's useful because then for each render you can disable/enable settings like rendering or not a plugin based on if the camera is moving or not.

**Comment by sheymann** [comment]
A similar issue was with `graph.attach`, I've added [`graph.attachBefore`](https://github.com/Linkurious/linkurious.js/blob/linkurious-version/src/classes/sigma.classes.graph.js#L292) long time ago.

You may get inspired by this for your PR.

**Comment by sheymann** [comment]
Also submitted to Sigma https://github.com/jacomyal/sigma.js/pull/606
