### ISSUE TITLE
Bug at example file: select-and-drag-nodes.html

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#155]
I'm getting the following error when trying to run the example `select-and-drag-nodes.html`:

Uncaught TypeError: select.bindDragNodes is not a function(anonymous function) @ select-and-drag-nodes.html:186

Any ideas why?

**Comment by sheymann** [comment]
Ah yes, I've made an update of sigma.plugins.select and `select.bindDragNodes` is no longer necessary.

**Comment by sheymann** [comment]
fixed in 76e65264c4eeff72bad0a7e3b459e7a6bcb31e27

**Comment by pablopareja** [comment]
cool thanks ;)

**Comment by mdamien** [comment]
This bug also affect `examples/drag-nodes.html`
