### ISSUE TITLE
glyphs events?

### ISSUE THREAD

**Issue by alfredopacino** [Linkurious/linkurious.js#157]
Hi, I can't find anything helpful, do you implemented some glyphs events handler (onhover, onclick) ?
thanks

**Comment by sheymann** [comment]
No we don't.

**Comment by alfredopacino** [comment]
ok, it could be useful.
Unrelated little question: can I force the glyphs content to be shown?

**Comment by sheymann** [comment]
Set `glyphThreshold` to 1, or to 0.1. It is the minimum size a node must have to see its glyph displayed.

**Comment by sheymann** [comment]
You can also decrease the Sigma setting `textThreshold`

**Comment by alfredopacino** [comment]
thanks!

**Comment by alfredopacino** [comment]
i'm sorry, what about a minSize glyph text?
I don't set the text size so it's proportional to the node size, but sometimes is too small 
![node](https://cloud.githubusercontent.com/assets/6325475/8696204/b54a0bc6-2aea-11e5-9766-d92e0c0d37a0.jpg)

**Comment by sheymann** [comment]
Sure, I've opened #178

**Comment by alfredopacino** [comment]
What if I want to render all the glyphs at same size no matter the node size?

**Comment by sheymann** [comment]
It is not possible. Would you like to submit a patch?

**Comment by alfredopacino** [comment]
in order to render all glyphs to a fixed 15 size sigma.renderers.glyphs.js row 140:
change
                 radius: glyph.size || node[prefix + 'size'] * defScale,

to
                 radius: glyph.size || 15 * defScale,

Obiouvsly it's a very rough hack, i'm not sure this file is the only one to hack for add a defaultGlyphSize general setting.

**Comment by sheymann** [comment]
`radius: glyph.size || ((fixedGlyphSize > 0) ? fixedGlyphSize : node[prefix + 'size']) * defScale` would be good, also don't forget to init `fixedGlyphSize`.

you can add the setting to https://github.com/Linkurious/linkurious.js/blob/linkurious-version/plugins/sigma.renderers.glyphs/settings.js, set 0 by default to remain backward-compatible.

**Comment by alfredopacino** [comment]
thanks, this feature should be merged in main project

**Comment by sheymann** [comment]
I'll merge it if you submit a PR.

**Comment by sheymann** [comment]
My mistake, the `glyphTextThreshold` setting is already available.
