### ISSUE TITLE
sigma.exporters.gexf creates a file having just one line

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#161]
I did some tests to export my graph to a file in `gexf` format and I just realized that the resulting file has all the contents in just a single line! :fearful: 
Is that behavior expected?

**Comment by sheymann** [comment]
Yes, you can use an XML prettifier such as http://xmlbeautifier.com/ to get it indented.

**Comment by pablopareja** [comment]
I would be nice to have such a functionality already included as part of linkurious.js

**Comment by sheymann** [comment]
must find a good xml prettifier

https://gist.github.com/sente/1083506 ?
