### ISSUE TITLE
Loading gexf file previously created with sigma.exporters.gexf doesn't work...

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#162]
I'm getting the following exception when trying to load a file I just exported using sigma.exporters.gexf

```
Uncaught TypeError: Cannot read property 'getElementsByTagName' of nullGraph 
@ gexf-parser.js:205(anonymous function) 
@ gexf-parser.js:524xhr.onreadystatechange 
@ gexf-parser.js:507
```

**Comment by pablopareja** [comment]
so, any ideas why this might be happening?

**Comment by sheymann** [comment]
I'm on it

**Comment by pablopareja** [comment]
great thanks :wink:

**Comment by pablopareja** [comment]
I was testing it again after adding the changes from your last commit but I keep getting the same error.... :confused:

**Comment by sheymann** [comment]
I am able to export the graph from plugin-exporters-gexf.html and to load it with load-external-gexf.html , so can you send me your gexf please? Also be sure to serve the file from a web server.

**Comment by pablopareja** [comment]
I just created this public gist with the gexf file that I generated: https://gist.github.com/pablopareja/2fa3ea939acaa5cc157e

Thanks!

**Comment by sheymann** [comment]
`xmlns:schemaLocation`

you haven't pulled the latest changes from the branch linkurious-version.

**Comment by pablopareja** [comment]
You were right, it works now :wink:
