### ISSUE TITLE
this.contexts.nodes.clear is null

### ISSUE THREAD

**Issue by panagiotidi** [Linkurious/linkurious.js#165]
When trying to open renderers-linkurious.html it does not load with the error that "this.contexts.nodes.clear" is null (sigma.renderers.webgl.js, line 584). I just downloaded the latest code, so, is there a chance this is being tackled with?

**Comment by mdamien** [comment]
This is most likely because you don't have webgl activated and you try to run a webgl renderer.

You can check if your webgl is activated via https://get.webgl.org/.

An issue here is that the webgl render doesn't provide any warning, this could be useful.

**Comment by panagiotidi** [comment]
Thanks for the help. Indeed there is no warning. Cheers
