### ISSUE TITLE
Optimize edge label alignment via a better measureText()

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#167]
The `edgeLabelAlignment` setting can be either `horizontal` or `auto`. If it's in `auto` it's gonna measure the text to know there is enough space to put it aligned. [The code](https://github.com/Linkurious/linkurious.js/blob/bench/edge-labels/plugins/sigma.renderers.edgeLabels/sigma.canvas.edges.labels.def.js#L81-L96)

During a performance analysis of the edges labels rendering, I found that measuring the text is a big performance hit compared to it's usefulness.

See the [bench/edge-labels](https://github.com/Linkurious/linkurious.js/tree/bench/edge-labels) branch. This is the result:
 ![results](http://i.imgur.com/h4sNVVV.png)

By ignoring the text length, we save 10ms of a 40ms render.

The proposed change would be something like:

```javascript
if ('auto' === settings('edgeLabelAlignment')) {
  var
    labelWidth = context.measureText(edge.label).width,
    edgeLength = sigma.utils.getDistance(
      source[prefix + 'x'],
      source[prefix + 'y'],
      target[prefix + 'x'],
      target[prefix + 'y']);

    // reduce node sizes + constant
    edgeLength = edgeLength - source[prefix + 'size'] - target[prefix + 'size'] - 10;

  if (labelWidth < edgeLength) {
    angle = Math.atan2(dY * sign, dX * sign);
  }
} else if('align' === settings('edgeLabelAlignment')){
  angle = Math.atan2(dY * sign, dX * sign);
}
```

**Comment by sheymann** [comment]
I agree to add an extra option.

But how can we increase perf while still using 'auto'? It is a useful feature on dense graphs and we use it in Linkurious Enterprise.

Maybe caching labelWidth? But caching is hard to invalidate.

Or we could approximate the calculation by measuring, at startup, the average width of capital letters (because they should be larger than other letters and digits) of this font at the specified font size:

```js 
var letterWidth = context.measureText('ABC...Z').width / 24;
```

then we multiply the average letter length by the number of letters of the label:

```js 
var labelWidth = edge.label.length * letterWidth;
```

This approach leads to an upper bound of the label width, which is good for the purpose of the 'auto' option: if text is larger than edge length, the label is not aligned with the edge.

**Comment by sheymann** [comment]
Notice that `measureText()` is also used in the [node hover](https://github.com/Linkurious/linkurious.js/blob/linkurious-version/plugins/sigma.renderers.linkurious/canvas/sigma.canvas.hovers.def.js#L115) renderer (3 times)

**Comment by mdamien** [comment]
yes, and we could even use directly the fontSize as the heuristic for the average length (since most fonts are rectangular). Maybe behind a setting (`approximateTextLength`) and then use a new measureText fonction function it in all the the labels renderers.

**Comment by sheymann** [comment]
It would be nice not to add another setting :)

**Comment by mdamien** [comment]
I agree too :+1:

**Comment by mdamien** [comment]
Gonna implement that transparently in the edge labels plugin and then we will see if we want to use it elsewhere

**Comment by mdamien** [comment]
A simple heuristic that's working well: 
```javascript
labelWidth = 0.5*edge.label.lvength*fontSize;
```
Only thing: That's assuming using latin-like languages.

**Comment by sheymann** [comment]
So we'll need a setting to enable/disable label width approximation.

**Comment by sheymann** [comment]
done

**Comment by sheymann** [comment]
Node labels are optimized, let's do the same for edge labels in renderers.edgeLabels
