### ISSUE TITLE
Add possibility to have `pre` and `post` hooks to canvas renderers

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#169]
Add the possibility for the `def` method in the canvas renderers to have `pre` and `post` hooks:

```
xyz.def = {
   pre: function(...){ this.font = "";},
   render: function(..){..use this.font as a context.font cache...},
   post: function(...){..clean things..},
}
```

The previous renderers.def won't need to be changed, this is gonna be compatible with the two models

It's to solve #167 and #168, and also because it would be nice for future optimizations (batch rendering for example).

Other possible solution:

* Pass all the objects to render together in one `renderAll` function to the renderer: More generic but would be harder to implement and wouldn't integrate well with the previous model

**Comment by sheymann** [comment]
How would it be compatible with current renderers?

**Comment by mdamien** [comment]
I would detect if the renderer.def is a function or an object and if it's a function, act as before

**Comment by mdamien** [comment]
Another possible solution:

* have the renderer be able to register to the `beforeRender` and `render` events

**Comment by mdamien** [comment]
The proposed solution wouldn't work because I couldn't share variable between the `pre()`,`render()` and `post()` function. So, now I leaning towards a version with an `init()` function like this SO answer: http://stackoverflow.com/questions/3590685/accessing-this-from-within-an-objects-inline-function

**Comment by mdamien** [comment]
Having `def` as an object can break plugins such as `customeEdgesShapes` assuming that def is a function. [Example in tapered](https://github.com/Linkurious/linkurious.js/blob/plugin/customEdgeShapes/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.tapered.js#L119)

**Comment by sheymann** [comment]
We can easily update these plugins.

**Comment by mdamien** [comment]
If we want to be more drastic and not keep any legacy: We could switch all the renderers to the new model.

**Comment by mdamien** [comment]
A first draft: https://github.com/Linkurious/linkurious.js/commit/d73d7a7c7a5d7f2d554085e020a7ea836c370e4e

**Comment by mdamien** [comment]
There are a few plugins which continue to assume that the renderer is a def function, here are a few fixes I need to do:

```
/home/linku/prog/linkurious.js/plugins/sigma.plugins.design/sigma.plugins.design.js:
  532              if (!(visualVar in self.originalVisualVariable[item.id])) {
  533                // non-writable property
  534:               Object.defineProperty(self.originalVisualVariable[item.id], visualVar, {
  535                 enumerable: true,
  536                 value: item[visualVar]

/home/linku/prog/linkurious.js/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.dashed.js:
  107      if (sigma.canvas.edges.labels) {
  108        edge.hover = true;
  109:       sigma.canvas.edges.labels.def(edge, source, target, context, settings);
  110        edge.hover = false;
  111      }

/home/linku/prog/linkurious.js/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.dotted.js:
  107      if (sigma.canvas.edges.labels) {
  108        edge.hover = true;
  109:       sigma.canvas.edges.labels.def(edge, source, target, context, settings);
  110        edge.hover = false;
  111      }

/home/linku/prog/linkurious.js/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.parallel.js:
  120      if (sigma.canvas.edges.labels) {
  121        edge.hover = true;
  122:       sigma.canvas.edges.labels.def(edge, source, target, context, settings);
  123        edge.hover = false;
  124      }

/home/linku/prog/linkurious.js/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.tapered.js:
  117      if (sigma.canvas.edges.labels) {
  118        edge.hover = true;
  119:       sigma.canvas.edges.labels.def(edge, source, target, context, settings);
  120        edge.hover = false;
  121      }



/home/linku/prog/linkurious.js/plugins/sigma.renderers.linkurious/canvas/sigma.canvas.extremities.def.js:
   18     * @param  {configurable}             settings     The settings function.
   19     */
   20:   sigma.canvas.extremities.def =
   21      function(edge, source, target, context, settings) {
   22      // Source Node:
   23      (
   24        sigma.canvas.hovers[source.type] ||
   25:       sigma.canvas.hovers.def
   26      ) (
   27        source, context, settings
   ..
   31      (
   32        sigma.canvas.hovers[target.type] ||
   33:       sigma.canvas.hovers.def
   34      ) (
   35        target, context, settings

/home/linku/prog/linkurious.js/plugins/sigma.renderers.linkurious/canvas/sigma.canvas.hovers.def.js:
   15     * @param  {configurable}             settings The settings function.
   16     */
   17:   sigma.canvas.hovers.def = function(node, context, settings) {
   18      var x,
   19          y,
   ..
   93  
   94      // Node:
   95:     var nodeRenderer = sigma.canvas.nodes[node.type] || sigma.canvas.nodes.def;
   96      nodeRenderer(node, context, settings, { color: color });
   97  
```

**Comment by mdamien** [comment]
Just discovered that in d3 there is similar pattern: `enter()/update()/exit()`

As noted in #214, this solution works for now but could be improved for some edge cases (renderers overlap, renderers using other renderers). One solution would be for def to accept either a simple item or multiple items (via a array or a generator)

**Comment by mdamien** [comment]
**Or we could remove pre/post** and use our own value caching for `ctx.font` like in [Phaser.js](https://github.com/photonstorm/phaser/blob/858ad5161028d45d65679c88fc1e9a08ceed1f8f/src/gameobjects/Text.js#L1216)

This solve the exact problem we have and would grow the solution accordingly to our needs.

But maybe this is pushing the problem to be solved later down the road

**Comment by sheymann** [comment]
If pre/post is overkill we should remove it.

**Comment by mdamien** [comment]
Ok, so we should revert https://github.com/Linkurious/linkurious.js/pull/203 and https://github.com/Linkurious/linkurious.js/pull/214

And have our own font caching..humm..let's try first to have a prototype with the ctx value caching to see which one is the most overkill

**Comment by mdamien** [comment]
I found two ways to remove the pre/post system:

**cache the font via a new context property: `context.font_cached**

```javascript
    var font_cache = this.contexts.labels.font;
    Object.defineProperty(this.contexts.labels, 'font_cached', {
      get: function() { return font_cache; },
      set: function(val) {
        if (val != font_cache){
          this.contexts.labels.font = val;
        }
        font_cache = val;
      },
    });
```

:heavy_plus_sign: : Easy to implement
:heavy_minus_sign: : A bit too magic, a bit too narrow

**add an optional `index` argument to the `.def` function**

```javascript
  sigma.canvas.edges.labels.def = {
    function(edge, source, target, context, settings, index) {
    index = index || 0;
    ....
    if ( index == 0 ) PREV_FONT = context.font;
    ....
```

:heavy_plus_sign: : Easy to implement, is equivalent to the pre/post system without breaking the renderer API
:heavy_minus_sign: : Do not solve the problem of inter-renderer interaction (other renderers changing the font value without use knowing)
