### ISSUE TITLE
Importing a Gexf file providing a File object instead of a path

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#170]
Hi, I would like to know whether it's possible to import a graph in gexf format directly providing a File javascript object (e.g returned by an input element) instead of a file path ?

**Comment by sheymann** [comment]
It is possible to pass a valid DOMElement instead of a file, see https://github.com/Linkurious/linkurious.js/blob/linkurious-version/plugins/sigma.parsers.gexf/sigma.parsers.gexf.js#L32

**Comment by pablopareja** [comment]
ok, and what about a String variable holding all the contents of the file?

**Comment by sheymann** [comment]
Convert the string to a DOMElement as follows and you're good to go:

```js
var parser = new DOMParser();
var domElement = parser.parseFromString(myString, "text/xml");
```

source: https://developer.mozilla.org/en-US/docs/Web/Guide/Parsing_and_serializing_XML

**Comment by pablopareja** [comment]
ok I just managed to get it working by using that piece of code.
Thanks!

**Comment by MartinGian** [comment]
Hi Pablo, I couldn't get the graph displayed on the page following this. 
Here's my question: https://github.com/Linkurious/linkurious.js/issues/386
Can you show me how you can do it? Thanks!
