### ISSUE TITLE
Issue with nodes position when exporting to Gexf file format

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#172]
It seems that the positions of nodes after applying a new layout to the graph are not stored when exporting the graph to a GEXF file. 
Is that behavior expected?
I am missing something when exporting the graph?

Here's the piece of code I'm using: 

```
function exportToGexf(){
     sigma1.toGEXF({
       download: true,
       filename: 'bio4jGraphExplorer.gexf',
       nodeAttributes: 'attributes',
       edgeAttributes: 'attributes',
       renderer: sigma1.renderers[0],
       creator: 'Biographika',
       description: 'Bio4j graph explorer'
     });
 }
```

**Comment by sheymann** [comment]
They should be exported. What is the output?

Do you use a webgl ou canvas renderer?

**Comment by pablopareja** [comment]
I'm using canvas but I managed to fixed it already, thanks!

**Comment by sheymann** [comment]
What did you do?

**Comment by pablopareja** [comment]
I hadn't realized that I had a piece of code coming from another example that was messing up with the nodes position... my fault :wink:

**Comment by sheymann** [comment]
okay
