### ISSUE TITLE
font awesome - graph icon won't show up

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#173]
this has me puzzled and may not be a Linkurious issue but perhaps some of you have run across it.

it seems that not all the icons in font-awesome font used by the Linkurious examples show up. I am assigning one of the little graphs icons (\uF201) to my nodes but for some reason it won't show up.  others show up but not this one.

I'm using the version of the font that's included in the Linkurious distribution but I also tried a direct reference to the CDN version, which seems to work even less, displaying little squares for most of icons I use.

thoughts?

**Comment by ekkis** [comment]
I tried using the CDN version again.  they may have fixed something because everything works fine now.  or perhaps I had a cache issue.  in any case, all the icons show up!

**Comment by sheymann** [comment]
Use `document.fonts` to wait for the end of font loading before initializing sigma. The browser will cache fonts so this is why the "bug" has disappeared the second time, but new visitors will still encounter the issue.

see https://github.com/Linkurious/linkurious.js/blob/linkurious-version/examples/renderers-linkurious-icons.html#L206

ref http://www.w3.org/TR/css-font-loading/

**Comment by ekkis** [comment]
oh, that's much better than just using the setTimeout as was done in `examples/plugin-customShapes-icons.html` where a note is made about a "shim" to the font loader.  thanks, I will use the document.fonts as you point out

**Comment by llp0574** [comment]
@sheymann What if I have multiple fonts?Can I trace the font I need?

**Comment by llp0574** [comment]
@sheymann @ekkis I found [a fantastic library](https://github.com/bramstein/fontfaceobserver) to solve this problem.

**Comment by ekkis** [comment]
@llp0574, it's cool.  thanks for sharing.  I've been meaning to look into how to use other font sets with linkurious.  just haven't gotten around to it
