### ISSUE TITLE
Question regarding the limit for zooming out 

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#176]
Hi,

I have realized that when interacting with my graph visualization there's a point where I cannot zoom out anymore and that is actually preventing me from seeing the whole picture of my graph and how clusters are organized.
Is that behavior expected? Could it be adjusted so that you can zoom out as much as you want?

**Comment by sheymann** [comment]
Decrease sigma [setting](https://github.com/Linkurious/linkurious.js/wiki/Settings) `zoomMin`

**Comment by sheymann** [comment]
Decrease sigma [setting](https://github.com/Linkurious/linkurious.js/wiki/Settings) `zoomMin`

**Comment by pablopareja** [comment]
ok, and what's the smallest possible value?

**Comment by sheymann** [comment]
I guess it's very close to 0

**Comment by sheymann** [comment]
Notice that it might be `zoomMax` instead, I always confound the two.

**Comment by pablopareja** [comment]
yeah you were right, it looks like it was `zoomMax` the one that I had to tweak for that :wink:
