### ISSUE TITLE
Fruchterman Reingold layout only working the first time that is called

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#177]
Here's the initialization of the listener:

```
var frListener = sigma.layouts.fruchtermanReingold.configure(sigma1, {
  iterations: 500,
  easing: 'quadraticInOut',
  duration: 800
});
```

and the line of code I'm using to start the layout calculation:

```
sigma.layouts.fruchtermanReingold.start(sigma1);
```

It works well the first time I call the start method _(even though everything freezes a bit till the layout calculation is done...)_. However once it's finished, it doesn't do anything anymore regardless how many times I call again the method `start`.
Do I have to configure the listener every time I call the start method?

**Comment by sheymann** [comment]
Looks like a bug re. start.

The freeze is normal because I've not encapsulated the algorithm into a web worker, so it runs on the main thread.

**Comment by pablopareja** [comment]
I see... so should I then create again the configuration in order to apply it more than once?

Thanks
