### ISSUE TITLE
renderers.glyphs: Add glyphTextThreshold setting

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#178]

**Comment by mdamien** [comment]
What's the difference with the current [`glyphTextThreshold`](https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.renderers.glyphs/sigma.renderers.glyphs.js#L42) setting ?

(Used here: [sigma.renderers.glyphs.js#L118](https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.renderers.glyphs/sigma.renderers.glyphs.js#L118))

**Comment by sheymann** [comment]
erf, nothing.
