### ISSUE TITLE
File exports fail in IE10+

### ISSUE THREAD

**Issue by apitts** [Linkurious/linkurious.js#185]
I am receiving this error message:
TypeError: Object doesn't support property or method 'remove'
And a traceback to: sigma.exporters.gexf.min.js:1:273

**Comment by sheymann** [comment]
same for:
- sigma.exporters.spreadsheet
- sigma.exporters.xlsx

**Comment by apitts** [comment]
Not sure how you feel about it @sheymann but adding fileSaver.js as a dependency for the plugins may solve the issue, no?
https://github.com/eligrey/FileSaver.js/

**Comment by sheymann** [comment]
Definitely no, FileSaver is not magic and also contains bugs.

**Comment by apitts** [comment]
I thought you might say that @sheymann! :smile: 

Thanks for the fixes.
