### ISSUE TITLE
Add plugin exporters.json

### ISSUE THREAD

**Issue by pablopareja** [Linkurious/linkurious.js#186]
Since there exists the possibility of importimg a graph from JSON format, why is there no method for exporting the graph to that same format?

**Comment by sheymann** [comment]
Because nobody needed it before you, so feel free to contribute!

**Comment by pablopareja** [comment]
hehe ok I will see if I can find some spare time for it :wink:

**Comment by sheymann** [comment]
`JSON.stringify(sigmaInstance.graph)` would do the trick and is propably compatible with sigma.parsers.json

**Comment by sheymann** [comment]
Did it work?

**Comment by sheymann** [comment]
@pablopareja Did it work?
