### ISSUE TITLE
Image export plugin - grainy image output

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#197]
We finally got the image plugin working, but we've found that the image quality created is really bad. Here are two images showing the difference between what is shown on screen and what is rendered in the downloaded image:

https://www.evernote.com/l/AE2zfvRV39ZMGZt5earqfSbl4d9gGGcnFN8

Is there some setting that I need to use to make it create softer edges on the objects in the image?

Andrew

**Comment by sheymann** [comment]
Can you copy-paste the code that calls the plugin?

**Comment by emergingdzns** [comment]
Here is the line that executes it:
```
sigma.plugins.image(s, s.renderers[0], {download:true, background: '#ffffff', size: 1140, labels: true});
```
I set the size to 1140 because that's the size of the original graph. I also tried 1000.

**Comment by sheymann** [comment]
Are you using a retina display?

**Comment by emergingdzns** [comment]
Yes. Does that make a difference?

**Comment by sheymann** [comment]
Yes, a lot! See issue https://github.com/jacomyal/sigma.js/issues/180

**Comment by emergingdzns** [comment]
Thanks but that ticket seems to be referring to how the graph get pixelated on screen, which doesn't seem to be the case for me. On screen the canvas rendered graph is very nice. But the exported image, is the one that's not right. The exported image isn't soft and fuzzy with blurred lines, in fact it's quite the opposite. It's like there's no anti-aliasing or anything.

Maybe the ticket is related, but I don't see a solution to the problem. Or has one not been developed?

**Comment by sheymann** [comment]
It seems that antialiasing is not applied on offscreen canvas. What browser do you use?

**Comment by emergingdzns** [comment]
I've tested in both Firefox, Chrome and Safari (I know - terrible browser). I haven't had a chance to get to a Windows machine to try it there.

**Comment by sheymann** [comment]
does it happen using examples/plugin-image.html ?

**Comment by sheymann** [comment]
fixed for [Ogma](https://linkurio.us/ogma-js-library-large-scale-graph-visualization/).
