### ISSUE TITLE
plugins.tooltip: delay hide execution on outNode and outEdge

### ISSUE THREAD

**Issue by alfredopacino** [Linkurious/linkurious.js#198]
I want to show in tooltip some control buttons (explode node/collapse node), there is a way to make the tooltip "persistent"? Currently I can't click o select something in the tooltip, it disappear on outNode event.
Something like an "active area" around the node :)

parallel question: can I switch from sigmajs to linkurious definitely without changing my code? Or there are sintax changes? Currently i'm importing linkurious plugins on my sigmajs installation.

**Comment by sheymann** [comment]
1) Use the `hide` option to define another event that will hide the tooltip such as `'clickStage'`, see https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.plugins.tooltips#configuration-options

2) There is no syntax changes, the two codebases are compatible and the changes we make on the core of sigma don't break plugins (unless you use a plugin that exist in sigma repos and has been updated in the linkurious repo, such as plugins.filter).

**Comment by alfredopacino** [comment]
the natural behaviour of a tooltip with buttons should be show on OverNode and a delay (like 0.5s) on outNode before the tooltip is hided..

**Comment by sheymann** [comment]
That would be a nice improvement indeed. Can you submit a PR that alter the following functions please?
https://github.com/Linkurious/linkurious.js/blob/linkurious-version/plugins/sigma.plugins.tooltips/sigma.plugins.tooltips.js#L380
https://github.com/Linkurious/linkurious.js/blob/linkurious-version/plugins/sigma.plugins.tooltips/sigma.plugins.tooltips.js#L436
https://github.com/Linkurious/linkurious.js/blob/linkurious-version/plugins/sigma.plugins.tooltips/sigma.plugins.tooltips.js#L492

**Comment by alfredopacino** [comment]
im sorry call me stupid but i never made a proper PR I tried but i'm not sure how to 'edit' files

**Comment by sheymann** [comment]
No worries, we'll make it right through the review process :)

**Comment by alfredopacino** [comment]
i closed the old pr and open a new one

**Comment by sheymann** [comment]
Fixed in https://github.com/Linkurious/linkurious.js/commit/69026397582170fa1ba61b6453f17bea77b2f636
