### ISSUE TITLE
[NEWS] Changes on the dev workflow

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#201]
We are about to change the way we develop plugins on linkurious.js. 

Until now, each plugin is crafted in its own branch (e.g. `plugin/tooltip`). The origin of that branch is the `master` branch, which is a clone of `jacomyal:sigma.js/master`. Working and testing on plugin branches ensures backward-compatibility with the repository `jacomyal:sigma.js`, and it is easy to create pull requests on it. Plugin branches are regularly merged into the branch `linkurious-version`, from which we build linkurious.js.

This workflow is good for these reasons:
- the commit history of each plugin is clean because it is the commit history of each branch.
- it ensures backward-compatiblity of plugins to the official sigma.js so that we can give back to sigma.js easily.

This workflow is bad for these reasons:
- it is difficult to contribute (to which branch should I create the pull request?).
- it is difficult to test the compatibility between multiple plugins (e.g. dragNodes and select).
- the commit history of linkurious.js is bloated with a lot of merges.

We have kept this approach during a complete year, with the hope that the evolution of `jacomyal:sigma.js` would make our efforts worth it. However the core of sigma.js has almost not evolved during the year, and pull requests on `jacomyal:sigma.js` are rarely reviewed.

Considering this state of things, we'll simplify the workflow on our end as follows:
- The branch `linkurious-version` will be renamed `develop`.
- The new branch `sigma` will be sync with `jacomyal:sigma.js/master`.
- The branch `master` will store the latest stable release.
- new plugins will be created in a separate branch from `develop`.
- plugin branches will disappear once they are considered stable by their author, and merged into `develop`.
- changes made in `/src`, i.e. the core of sigma.js, will continue to be submitted to `jacomyal:sigma.js/master` as pull requests.

From linkurious.js v1.1, we will authorize breaking changes in the core of sigma.js. Plugin authors will eventually check the compatiblitiy with `jacomyal:sigma.js` at will.

**Comment by mdamien** [comment]
I found a more standard way of doing this: `master` is the current development branch and `stable` is the latest release branch. What do you think ?

**Comment by sheymann** [comment]
Other repositories of Linkurious use `develop` as current development branch and `master` as latest release branch, so let's stick with it.

**Comment by sheymann** [comment]
@davidrapin for history

**Comment by davidrapin** [comment]
` master` /` stable` seems reasonable and standard, but we'll have to change a couple of build/CI scripts, when do you want to do this?
