### ISSUE TITLE
Be available on cdnjs

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#205]
To make it easier for people to use linkurious.js, people shouldn't have to build themselves the library.

A first step would be to be available on https://cdnjs.com/ . I keep bower, npm and a `dist/` folder for other issues.

**Comment by mdamien** [comment]
Thinking about it, I think that we should first have a `dist/` folder and then adding it do cdnjs would be cool

**Comment by sheymann** [comment]
rel #210

**Comment by mdamien** [comment]
An even better solution is the `cdn.rawgit.com` cdn I think, the files would be tied to the version but it's easy to setup (nothing to do)

**Comment by sheymann** [comment]
bof: https://rawgit.com/faq#no-uptime-guarantee

**Comment by mdamien** [comment]
Not important for now, let's wait for somebody to ask this
