### ISSUE TITLE
renderer.linkurious: Avoid floating-point coordinates and use integers instead on drawImage

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#206]
`context.drawImage` is called to render images on nodes, e.g. https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.renderers.linkurious/canvas/sigma.canvas.nodes.def.js#L44

use `Math.round`

ref: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas

**Comment by mdamien** [comment]
The original author provide a test : http://seb.ly/demos/bunnybench/bunnies_canvas.html

On my machine:

   * Chrome, FPS is worse with pixel-snapping
   * Firefox, FPS is better with pixel-snapping

Performance is hard.

**Comment by sheymann** [comment]
bad idea: https://github.com/Linkurious/linkurious.js/pull/212#issuecomment-125137742
