### ISSUE TITLE
zoomToNode vs Tooltip plugin

### ISSUE THREAD

**Issue by alfredopacino** [Linkurious/linkurious.js#209]
I use this code to accomplish a zoom to Clicked node
```
sigma.prototype.zoomToNode = function(node, ratio, camera){
	console.log(camera)
    if(typeof camera == "undefined"){
        camera = this.cameras[0];
    }
	sigma.misc.animation.camera(camera, {
  ratio: 1 / camera.settings('zoomingRatio'),
  x:node[camera.readPrefix+"x"],
  y:node[camera.readPrefix+"y"]
}, {
  duration: 1000
});

    this.refresh();
}
```

but the problem, with a tooltip configured to be shown on ClickNode, is the tooltip doesn't follow the x,y movement. Not sure it's clear: basically the tooltip should change the coords as the zoomToNode event does.

Maybe a solution could be open the tooltip as callback of the animation ..

**Comment by sheymann** [comment]
The solution is indeed to open the tooltip in the callback, otherwise it would hurt performance to try to make it stick to the changing node coordinates on screen.

**Comment by alfredopacino** [comment]
Yes, there is a way for accomplish that? In other words, how can I set the tooltip plugin for show the tooltip NOT in the defined event (defined in tooltip config) but just as callback of my function?

**Comment by sheymann** [comment]
Use the `tooltipInstance.open()` function to open a tooltip manually, and `tooltipInstance.close()` to close the current tooltip. Maybe configure `node.show: null` to prevent node tooltip to open on event.

**Comment by alfredopacino** [comment]
not sure about the correct syntax for the callback of this plugin
```
   sigma.prototype.zoomToNode = function(node, ratio, camera){
	console.log(camera)
    if(typeof camera == "undefined"){
        camera = this.cameras[0];
    }
	sigma.misc.animation.camera(camera, {
  ratio: 1 / camera.settings('zoomingRatio'),
  x:node[camera.readPrefix+"x"],
  y:node[camera.readPrefix+"y"]
}, {
  duration: 1000
}, function(){ tooltips.open(); });
	
    this.refresh();
}
```
doesn't work

**Comment by alfredopacino** [comment]
Here defined a callback function, but I have to problems:
I don't know how to add the clicked node as parameter to the callback function.
And also, the tooltip even with this cose with fixed node  s.graph.nodes('root') doesn't show up!
```
function opentooltip(){
var n = s.graph.nodes('root')
console.log('callback');
var prefix = s.renderers[0].camera.prefix;
tooltips.open(n, config.node, n[prefix + 'x'], n[prefix + 'y']);

}
sigma.prototype.zoomToNode = function(node, ratio, camera, callback){
	console.log(camera)
    if(typeof camera == "undefined"){
        camera = this.cameras[0];
    }
	sigma.misc.animation.camera(camera, {
  ratio: 1 / camera.settings('zoomingRatio'),
  x:node[camera.readPrefix+"x"],
  y:node[camera.readPrefix+"y"]
}, {
  duration: 1000,
  onComplete: callback
});
    this.refresh();
}
```

**Comment by sheymann** [comment]
`callback(node)``is called instead of `opentooltip(node)` :)

**Comment by alfredopacino** [comment]
nop, actually that console.log('callback'); is printed correctly (after the animation) but nothing happen on tooltips.open().
The problem is tooltips.open() indeed, i tried even outside those functions..it's like the manual tooltip open doesn't work.

**Comment by sheymann** [comment]
It should be compatible. I'd need the complete source code to debug.

**Comment by alfredopacino** [comment]
I found out it's a tooltip position problem. It's just outside the container div, but it's there (not sure why it works if i not use manual tooltip open..).
I don't have a s.renderers[0].camera.prefix field.
I have a s.renderers[0].camera.readPrefix, but even with this field the position is wrong.
I sent you the link via email.

**Comment by sheymann** [comment]
Do you use canvas or webgl?

**Comment by alfredopacino** [comment]
canvas, thanks!

**Comment by alfredopacino** [comment]
please note the graph-container have a margin left and right, whom changes when i hide left or right column. I think that's part of the problem.

**Comment by alfredopacino** [comment]
maybe you figure it out the problem? tomorrow is my deadline :)

**Comment by sheymann** [comment]
It is an issue with CSS positionning. The tooltip is in the DOM (class="sigma-tooltip top"). I was able to display the tooltip by changing the left and top CSS properties of the tooltip, but you'll need to experiment:

- invert left and top values so that they are positive numbers
- substract the left column with from and top navbar height

**Comment by alfredopacino** [comment]
i noticed that too, as i said it's a css issue :)

**Comment by sheymann** [comment]
What happens if you use the camera.readPrefix instead of camera.prefix in:

```js
var prefix = s.renderers[0].camera.prefix;
tooltips.open(n, config.node, n[prefix + 'x'], n[prefix + 'y']);
```

**Comment by alfredopacino** [comment]
it's looks like different tooltip position, but still wrong and outside the div..

**Comment by sheymann** [comment]
Use `var prefix = 'renderer1'` instead of `var prefix = s.renderers[0].camera.readPrefix;`

**Comment by sheymann** [comment]
and edit sigma.plugins.tooltips:
- line 179 replace `x = ~~(x - containerRect.left);` by `x = ~~(x + containerRect.left);`
- line 180 replace `y = ~~(y - containerRect.top);` by `y = ~~(y + containerRect.top);`

**Comment by alfredopacino** [comment]
the X coords is not perfect (maybe i just should add the div container marginleft) but the Y is still outside the div :/
i updated the edit

**Comment by alfredopacino** [comment]
still unsolved.. :/

**Comment by alfredopacino** [comment]
rough temp edit who make the tooltip works fine:
   function opentooltip(n){
console.log('callback');
var prefix = 'renderer1:';
var marginright=parseInt($('#reference_network').css('margin-right'))
var marginleft=parseInt($('#page-wrapper').css('margin-left'))
var width=parseInt($('#reference_network').css('width'))

console.log(n[prefix + 'x']);

console.log('marginleft:'+marginleft+' marginright:'+marginright+' width:'+width)
tooltips.open(n, config.node, parseFloat(n[prefix + 'x']-marginleft-10), n[prefix + 'y']-70);
}

**Comment by sheymann** [comment]
@alfredopacino please test with the latest changes https://github.com/Linkurious/linkurious.js/commit/7b388444f7029a6d024f79e1d4a28470bc298096 should fix the issue.

```js
function opentooltip(n){
  console.log('callback');
  var prefix = 'renderer1:';
  tooltips.open(n, config.node, n[prefix + 'x'], n[prefix + 'y']);
}
```

**Comment by alfredopacino** [comment]
awesome, thanks

**Comment by sheymann** [comment]
@alfredopacino is the graph container of sigma positionned in absolute?

**Comment by alfredopacino** [comment]
yes, absolute.
as I said in last post, with your latest tooltip plugin fix I solved :)

**Comment by sheymann** [comment]
Yeah but the fix introduced another bug in positionning so I'm trying to better understand what's going on.

**Comment by alfredopacino** [comment]
ok you can see my code in the url i sent you (just remove the underscore)
