### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#210]
Here are a few things I noted to make it easier to work with sigma

* [x] Add dist/ folder with latest release => #208 
* [x] bundle all plugins in one file
* [x] Be on npm https://github.com/jacomyal/sigma.js/issues/186 , https://github.com/pombredanne/sigma.js/pull/1#commitcomment-5227010
* ~~Have a copy-pastable example in the README~~ let's do that with #55 

My main focus of optimization being the time between a dev thinking "I want to display a graph" to doing it

**Comment by mdamien** [comment]
A note, for npm, people already use linkurious  in their package.json: https://github.com/sim51/tank-browser/blob/master/package.json#L37

Being on bower would force us to have a `bower.json` and bower it's less and less used now. So let's abandon the bower integration (and focus on good bundle+be available on npm)

**Comment by sheymann** [comment]
https://github.com/Linkurious/linkurious.js/wiki/How-to-publish-on-npm

**Comment by sheymann** [comment]
published: https://www.npmjs.com/package/linkurious
