### ISSUE TITLE
`onMove` render two times during a panning event

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#213]
As found in #211, `onMove` is called two times during panning

![chart](http://i.imgur.com/aJnee6q.png)

After a bit of detective work, `onMove` is binded to `mousemove` and `render` so it's why it's called two times.

https://github.com/Linkurious/linkurious.js/blob/develop/src/misc/sigma.misc.bindEvents.js#L499-L503

```javascript
      // Bind events:
      captor.bind('click', onClick);
      captor.bind('mousedown', onMove);
      captor.bind('mouseup', onMove);
      captor.bind('mousemove', onMove);
      captor.bind('mouseout', onOut);
      captor.bind('doubleclick', onDoubleClick);
      captor.bind('rightclick', onRightClick);
      self.bind('render', onMove);
    }
```

Removing `self.bind('render', onMove);` fix the bug

**Comment by mdamien** [comment]
How this bug was introduced: https://github.com/Linkurious/linkurious.js/commit/fca91dcc1aed9a3741d2cacad60c6f4f1a126fd2

**Comment by mdamien** [comment]
After some testing, I also discovered that mouse move events are stacking, we should throttle them.

**Comment by sheymann** [comment]
What is the performance gain?

**Comment by mdamien** [comment]
We go from this:

![old](http://i.imgur.com/CBFDvl7.png)

to this

![new](http://i.imgur.com/1nUtxhs.png)

But the **performance is nearly the same** (since drawing the hovers is very fast).

It looks like the bottleneck is onMove bouncing like hell:

![bouncing](http://i.imgur.com/oQFZP2y.png)

So, a solution to make the panning really smooth would be to use `requestAnimationFrame` for the refresh. And to have each canvas be set as dirty or not. This is not very chirurgical, I'm working on finding a simpler solution.

**Comment by sheymann** [comment]
From the screenshots: takes ~400ms to ~70ms

**Comment by mdamien** [comment]
Huummm...https://github.com/Linkurious/linkurious.js/blob/develop/src/misc/sigma.misc.drawHovers.js#L49-L51

**Comment by mdamien** [comment]
In fact, now I think it's not bubbling: the `draw()` function is called each time there is an `overEdge` event. Which can be quite expensive with 100 edges.

https://github.com/Linkurious/linkurious.js/blob/develop/src/misc/sigma.misc.drawHovers.js#L36-L42

**Comment by sheymann** [comment]
Don't forget that this `draw` function only refreshes the hover canvas, leaving other canvas untouched so it's quite cheap.

**Comment by mdamien** [comment]
yes, but it can calls draw many times per `mousemove` (2 times the number of edges + the number of nodes selected).

A simple solution would be to listen to the `out/overEdges` and `out/overNodes` instead of `out/overEdge` and `out/overNode`. Making it only 4 calls max. (so 4 calls to `draw()`).

And to simplify everything we could remove `over/outXXX` and just have one event `udpateHover` with everything in it.

**Comment by sheymann** [comment]
I agree on binding to `out/overEdges` and `out/overNodes`.

However `out/overXXX` are events that can be used by integrators and other plugin developers so we should not remove them.

**Comment by mdamien** [comment]
If find it easier for integrators to have a `updateHovers` with the current hovered nodes and edges instead of telling them the diff.

**Comment by sheymann** [comment]
`updateHovers` is opinionated on an application of the visualization state, while `out/over` events only describes a state so are more neutral.

**Comment by mdamien** [comment]
Hum, in `updateHovers` you can also put the newly hovered nodes. We just bundle everything together instead of having many small events.

**Comment by sheymann** [comment]
Let's write a clear specification for this.

**Comment by mdamien** [comment]
Something like:

```javascript       
self.dispatchEvent('updateHovers', {
          hovered: {
            edges: currHoveredEdges,
            nodes: currHoveredNodes,
          },
          newOver:{
            edges: newOverEdges,
            nodes: newOutNodes,
          },
          newOut:{
            nodes: newOutNodes,
            edges: newOverNodes,
          },
          captor: e.data
        });
```

With the `newOver` and `newOut` being optional if we keep the old events.

Something also: we could remove remove most of `drawHovers.js` and just call it like the `draw` function.

**Comment by sheymann** [comment]
How about this and we remove the old events?

```js
self.dispatchEvent('mouseover', {
          target: {
            nodes: currHoveredNodes,
            edges: currHoveredEdges,
          },
          enter: {
            nodes: newOutNodes,
            edges: newOverEdges,
          },
          leave: {
            nodes: newOutNodes,
            edges: newOverNodes,
          },
          captor: e.data
});
```

**Comment by mdamien** [comment]
Nice! :+1: Let's do that

**Comment by sheymann** [comment]
Need further testing

**Comment by sheymann** [comment]
@mdamien can you provide a patch for sigma.plugins.tooltips to handle this event please? Tooltips can be shown on overNode and overEdge, and be hidden on outNode and outEdge events. A tooltip should be related to a single node or edge.

**Comment by sheymann** [comment]
@mdamien sigma.plugins.dragNodes is also broken because it uses overNode and outNode events.

**Comment by sheymann** [comment]
Bug: on leaving an edge, data.leave.edges is empty. See events.html on mouseover event.

**Comment by sheymann** [comment]
@mdamien  Panning on a WebGL renderer has become dead slow.

**Comment by mdamien** [comment]
I can't reproduce the WebGL bug.

For the plugins (tooltips, drag), I can put `overNode/Edge` and `outNode` back so we don't need to modify too much the plugins.

For the `data.leave.edges`, I did something stupid:

```javascript
            leave: {
              nodes: newOutNodes,
              edges: newOutNodes, <-- oops
            },
            captor: e.data
```

**Comment by sheymann** [comment]
It's better to update the plugins. It will be easy as they bind to the old events, we just need to use the new event. It will also be clearer how developers will use the new event.

**Comment by mdamien** [comment]
We should also maybe rename the event to something that don't conflict with an existing DOM event. Something like `hoversUpdated` or just `hovers`.

**Comment by sheymann** [comment]
It is really an issue?

**Comment by mdamien** [comment]
No, it's just to make it clear that it's a sigma event

**Comment by sheymann** [comment]
Good point, so let's say `hovers`

**Comment by sheymann** [comment]
New event:

```js
'hovers', {
  current: {
    nodes: currHoveredNodes,
    edges: currHoveredEdges,
  },
  enter: {
    nodes: newOverNodes,
    edges: newOverEdges,
  },
  leave: {
    nodes: newOutNodes,
    edges: newOutNodes,
  },
  captor: e.data
}
```
