### ISSUE TITLE
Add automated browser compatibility testing

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#219]
Running it via BrowserStack (we already have an open-source plan there).

It could run:

* the unit tests
* the examples
* a simple benchmark

**Comment by sheymann** [comment]
- Benchmarks with realistic interactions

**Comment by mdamien** [comment]
A [basic script that check for errors](https://github.com/Linkurious/linkurious.js/blob/4ff3d3d6862e22820fffec3c3254899c1fdf8375/scripts/check-errors.py)  was added. it just looks for js errors and it does not interaction for now but it's working and you can see that the `neo4j-query` examples isn't working for example.

**Comment by sheymann** [comment]
will be done in next major release.
