### ISSUE TITLE
Edges not rendered when extremities are far from the viewport

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#224]
Currently edges are rendered if one of their extremities is inside the viewport + margin (look for `edgesOnScreen` variable). As a consequence, edges with extremities far from the viewport but that goes through the viewport are hidden.

This side effect may be a desired feature when zooming in a dense network, but it is a bug most of the time. Let's code a more accurate way to identify the edges to render.

**Comment by mdamien** [comment]
Here is the specific code:
https://github.com/Linkurious/linkurious.js/blob/develop/src/renderers/sigma.renderers.canvas.js#L280-L287

```javascript
      for (a = graph.edges(), i = 0, l = a.length; i < l; i++) {
        o = a[i];
        if (
          (index[o.source] || index[o.target]) &&
          (!o.hidden && !nodes(o.source).hidden && !nodes(o.target).hidden)
        )
          this.edgesOnScreen.push(o);
      }
```

So it's just: `at least one extremity visible => show edge`

The margin being from:

```javascript
    this.nodesOnScreen = this.camera.quadtree.area(
      this.camera.getRectangle(this.width, this.height)
    );
```

So, it's why it feels a bit random. To know if a node is visible, we use the quadtree.

**Comment by sheymann** [comment]
The test should not rely on nodes anymore: if two nodes are not displayed but they are linked by an edge that crosses the viewport, we should display the edge.

**Comment by mdamien** [comment]
The most intuitive thing would be to use `edgequadtree` to find thecorresponding edges, like this:

```javascript
this.edgesOnScreen = this.camera.edgequadtree.area(
  this.camera.getRectangle(this.width, this.height)
);
```

But `edgequadtree.area` returns nothing for now

**Comment by mdamien** [comment]
First try with edgequad

![try1](http://i.imgur.com/6iWOBMG.png?1)

*The black box being the current viewport and the edges the one detected to be visible by the edgequad*

There are a lot of false positives since we are using bounding boxes.

**Comment by mdamien** [comment]
So. It's a big performance hit for large and dense graph but it keeps a nice consistency. Especially for small graph, let's add a threshold ? `500` edges seems cool as a default

**Comment by sheymann** [comment]
No threshold, please propose a setting

**Comment by mdamien** [comment]
Yep, it's what I was thinking

**Comment by sheymann** [comment]
true/false setting?

**Comment by mdamien** [comment]
In Leaflet, [they do lineClipping](https://github.com/Leaflet/Leaflet/blob/45034155bdf8d958554b43ed8dbd7020df9ca6ab/src/geometry/LineUtil.js#L97-L131). We could use the same approach to eliminate a lot of useless rendering (labels especially).

**Comment by sheymann** [comment]
the issue is to calculate the clipping :)

**Comment by mdamien** [comment]
diff --git src/renderers/sigma.renderers.canvas.js src/renderers/sigma.renderers.canvas.js
index f35440a..bc3b355 100644
For history, here's the patch using the edgequadtree. It becomes unusable with more than 500 nodes.

A few things:
 
* drawing offscreen should have no performance effect, currently it has (responsibility of the renderers to not draw offcanvas?)
* edgequadtree should be optimized if we want to include it in the hot path of the rendering like this
* performance is equivalent to getting `this.graph.edges();` directly

```patch
--- src/renderers/sigma.renderers.canvas.js
+++ src/renderers/sigma.renderers.canvas.js
@@ -252,7 +252,6 @@
         conrad.killJob(k);
 
     // Find which nodes are on screen:
-    this.edgesOnScreen = [];
     this.nodesOnScreen = this.camera.quadtree.area(
       this.camera.getRectangle(this.width, this.height)
     );
@@ -264,18 +263,9 @@
     // - If settings('batchEdgesDrawing') is true, the edges are displayed per
     //   batches. If not, they are drawn in one frame.
     if (drawEdges) {
-      // First, let's identify which edges to draw. To do this, we just keep
-      // every edges that have at least one extremity displayed according to
-      // the quadtree and the "hidden" attribute. We also do not keep hidden
-      // edges.
-      for (a = graph.edges(), i = 0, l = a.length; i < l; i++) {
-        o = a[i];
-        if (
-          (index[o.source] || index[o.target]) &&
-          (!o.hidden && !nodes(o.source).hidden && !nodes(o.target).hidden)
-        )
-          this.edgesOnScreen.push(o);
-      }
+      this.edgesOnScreen = this.camera.edgequadtree.area(
+        this.camera.getRectangle(this.width, this.height)
+      );
 
       // If the "batchEdgesDrawing" settings is true, edges are batched:
       if (embedSettings('batchEdgesDrawing')) {
diff --git src/sigma.core.js src/sigma.core.js
index ce39084..cf61185 100644
--- src/sigma.core.js
+++ src/sigma.core.js
@@ -533,8 +533,7 @@
         // Refresh edgequadtree:
         if (
           c.edgequadtree !== undefined &&
-          c.settings('drawEdges') &&
-          c.settings('enableEdgeHovering')
+          c.settings('drawEdges')
         ) {
           c.edgequadtree.index(this.graph, {
             prefix: c.readPrefix,
```

Gonna add a setting `edgesClippingWithNodes` and do a PR

**Comment by mdamien** [comment]
Edge clipping working correcly, do we close the issue ?

**Comment by sheymann** [comment]
- new setting: edgesClippingWithNodes
