### ISSUE TITLE
Rename node.fixed to node.pinned

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#225]
Layouts should not update the position of nodes with fixed/pinned to true. The attribute has a better meaning with pinned instead of fixed.

**Comment by mdamien** [comment]
:+1: +1 !

**Comment by sheymann** [comment]
Need to update layouts

**Comment by sheymann** [comment]
closed as done in next major release

**Comment by mdamien** [comment]
such changes, much awesomeness !
