### ISSUE TITLE
Edges labes doesnt show

### ISSUE THREAD

**Issue by emcom** [Linkurious/linkurious.js#228]
Hi, I am beginner and I am tryinng to show labes of edges.
During initialization of sigma I use setting drawEdgeLabels: true, so I got this error. sigma.renderers.canvas.js:283 Uncaught TypeError: Cannot read property 'def' of undefined. 

 Thnaks for help.

**Comment by mdamien** [comment]
Hi,

Here's an example on how to use it: [examples/edge-renderers.html](https://github.com/Linkurious/linkurious.js/blob/develop/examples/edge-renderers.html)

One easy error is to not include the `edgeLabels` plugin.

Here's [the example running](https://rawgit.com/Linkurious/linkurious.js/develop/examples/edge-renderers.html)

If it's not ok, can you provide a bit more info ?

**Comment by emcom** [comment]
Its work. Thanks for quick help!!!
