### ISSUE TITLE
Alert the user if webgl is not supported but trying to render with the WebGL renderer

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#229]
For now the error the user get is `Uncaught TypeError: Cannot read property 'clear' of null`.

We should maybe alert the user (via an alert for example) and make the renderer fail gracefully.

**Comment by sheymann** [comment]
We should fallback to canvas with a simple notice instead of an error.

**Comment by mdamien** [comment]
If the developer wants something like that, he should use the default renderer. Else it's suprising for him if all his plugins are for webgl and he really want to force webgl.

**Comment by sheymann** [comment]
So this error happens only when the webgl renderer is used explicitely?

**Comment by mdamien** [comment]
yep

**Comment by sheymann** [comment]
Can we do it for the next release?

**Comment by mdamien** [comment]
fine for me :v:
