### ISSUE TITLE
Multiple Selection

### ISSUE THREAD

**Issue by achenick** [Linkurious/linkurious.js#231]
I am writing to you this afternoon to ask a question about Linkurious' plugin. I am using the filter template and it does its job well, but I was wondering if I can do multiple filter for a specific category? Thank you so much! Have a blessed day!

**Comment by mdamien** [comment]
Yes, you can use the [example](https://rawgit.com/Linkurious/linkurious.js/develop/examples/filters.html) as a starting point and modify the [`nodesBy`](https://github.com/Linkurious/linkurious.js/blob/develop/examples/filters.html#L265-L273) condition to filter as you wish.

**Comment by achenick** [comment]
Thank you mdamien. Is there a way to filter it with checkboxes and do multiple filters?

**Comment by mdamien** [comment]
Of course, as you can see in the example, you can have as many filter in the panel (degree, category,..).

**Comment by achenick** [comment]
I have done that but what I am referring to is a multi-select like this one:

http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html

**Comment by mdamien** [comment]
I would like to help you but this doesn't looks like linkurious.js specific.

You need to refer to the `SumoSelect` documentation to find a way to get the `change` event and then update your current filter/graph accordingly.

**Comment by achenick** [comment]
I appreciate it thank you so much!

**Comment by mdamien** [comment]
You're welcome! :smiley:
