### ISSUE TITLE
labelTreshold setting is confusing

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#236]
``` javascript
    // {number} The minimum size a node must have to see its label displayed.
    labelThreshold: 8,
```

So you can expect something like a width in px and not displaying the label below this size.

But here's the label renderer code:

```javascript
  sigma.canvas.labels.def = function(node, context, settings, infos) {
    var fontSize,
        prefix = settings('prefix') || '',
        size = node[prefix + 'size'] || 1,
        ...;

    if (size < settings('labelThreshold'))
      return;
```

So it doesn't even look at the content of the label, just the size of the node.

here the size is set via the `rescale` middleware

```javascript
    ns = ~rescaleSettings.indexOf('nodeSize'),
    ....
    a = (settings('maxNodeSize') - settings('minNodeSize')) / sizeMax;
    b = +settings('minNodeSize');
    ....
    for (i = 0, l = n.length; i < l; i++) {
      n[i][writePrefix + 'size'] =
        n[i][readPrefix + 'size'] * (ns ? a : 1) + (ns ? b : 0);
```

So there is not correlation with the label width.

Result: In most examples, you have only one label that shows with the default zoom level and it's the just the biggest node.

**Comment by mdamien** [comment]
@sheymann is this ok to change what the setting do ?

**Comment by sheymann** [comment]
@mdamien I'm afraid it would hurt performance, as looking at the node size is faster than computing the text size.

**Comment by mdamien** [comment]
@sheymann depends if we use approximate text width

**Comment by sheymann** [comment]
It's worth trying it. Can you work on a separate branch?

**Comment by sheymann** [comment]
won't fix
