### ISSUE TITLE
Add AUTHORS file

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#238]
A file like this one: https://github.com/django/django/blob/master/AUTHORS where there is a clear attribution of who started the project, who contributed,...

**Comment by sheymann** [comment]
Tiresome to update, I've not found any cross-platform script to generate such file. A reference file is easier: https://github.com/Linkurious/linkurious.js/blob/develop/AUTHORS.md

**Comment by mdamien** [comment]
I think you should reference this: https://github.com/Linkurious/linkurious.js/graphs/contributors

**Comment by sheymann** [comment]
Bof, it provides too much statistics. I'd rather list authors by name.

**Comment by mdamien** [comment]
me too, it's why we should add the ~20s of people who did more than a typo fix to the AUTHORS and, bam, it's done !

**Comment by sheymann** [comment]
Agree, but need an automatic way to get the list.

**Comment by mdamien** [comment]
I could do it by hand for the first and then we would add people by people (like in the django project)

**Comment by sheymann** [comment]
ok

**Comment by sheymann** [comment]
:+1:
