### ISSUE TITLE
Nodes disappearing when zooming on custom container

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#243]
![image](https://cloud.githubusercontent.com/assets/1469823/9198647/cf17ac58-403d-11e5-84d5-a37f63f80d85.png)

Able to reproduce with the canvas renderer, with the webgl renderer it's only for the labels.

Looks like a problem with the detection of the `nodesOnScreen`

Example here: http://linkurious.github.io/linkurious.js/examples/force.html

**Comment by mdamien** [comment]
Wow, this is my minimal file to reproduce it:

```html
<!-- START SIGMA IMPORTS -->
<script src="../dist/sigma.js"></script>
<script src="../plugins/sigma.layout.forceAtlas2/worker.js"></script>
<script src="../plugins/sigma.layout.forceAtlas2/supervisor.js"></script>
<script src="../plugins/sigma.layout.forceLink/worker.js"></script>
<script src="../plugins/sigma.layout.forceLink/supervisor.js"></script>
<script src="../plugins/sigma.plugins.generators/sigma.plugins.generators.js"></script>
<style>
#graph-container { height: 100%; }
</style>
<div id="graph-container" class="well" style="padding: 0"></div>
<script>
g = sigma.plugins.generators.grid(12,12);

s = new sigma({
  graph: g,
  renderer: {
    container: 'graph-container',
    type: 'canvas'
  },
});

//s.startForceAtlas2(); // <- replace with forcealtas2 and it's working fine
sigma.layouts.startForceLink(s);
</script>
<pre> <!-- remove the <pre> and it's working fine -->
</pre>

```

**Comment by mdamien** [comment]
Solved: `forceLink` disable the indexation while running. So the `nodesOnScreen` and the `hovers` won't work

**Comment by apitts** [comment]
Quick question on this as I recall experiencing it a while ago. Is the status solved as per the above? Just wondering as the issue is still open.

**Comment by sheymann** [comment]
fixed for [Ogma](https://linkurio.us/ogma-js-library-large-scale-graph-visualization/).
