### ISSUE TITLE
No hovering or graph disappears when nodes are on the same axis

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#247]
Following https://github.com/jacomyal/sigma.js/issues/433, there's two place to fix when nodes are on the same axis:

* [x] drag nodes
* [x] edge hovering
* [x] drag not working if two first nodes are axis-aligned (even with lot of random nodes after)

[files to reproduce the two bugs](https://gist.github.com/mdamien/af825283f2e71d27192b)

**Comment by mdamien** [comment]
Gonna close this issue. Just one last thing to keep in mind is that the interpolation model of `dragNodes` does not allow you to move perfectly aligned nodes (if they are all perfectly aligned) on the axis they are aligned.

This would mean we would need to change the underlying logic of `dragnodes` to move perfectly aligned nodes on the axis they are aligned.

**Comment by sheymann** [comment]
So what would happen using dragNodes on perfectly aligned nodes?

**Comment by mdamien** [comment]
You can try with this file: https://gist.githubusercontent.com/mdamien/af825283f2e71d27192b/raw/69ea89776f51fe07bc88234ebaf6d2356fabb30d/bug_axis_aligned_drag.html

The nodes are only moving along one axis
