### ISSUE TITLE
Guard node coordinates values against bad values

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#249]
The idea is simple: Sometimes, the value of `node.x` or `node.y` can be set to bad values (null, undefined, string, object,...), we can make this impossible by throwing an error when the user try to do that:

```javascript
    var guard = function(prop) {
      var val = node[prop],
        getter = function() { return val; },
        setter = function(newval) {
          if (!newval) {
            throw new Error('Incorrect val for node.'+prop+': '+newval);
          }
          val = newval;
          return newval;
        };
          
      Object.defineProperty(validNode, prop, {
        get: getter,
        set: setter,
        enumerable: true,
        configurable: true,
      });
    };

    guard('x');
    guard('y');
```

Then, life will be easier and there will be many more rainbows in the world thanks to this :)

This can only be included after a good performance impact analysis but it looks like it doesn't influence performance.

**Comment by sheymann** [comment]
closed as done in next major release
