### ISSUE TITLE
fix retina display

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#25]
See https://github.com/jacomyal/sigma.js/issues/180

**Comment by mdamien** [comment]
It was solved but commented out [here](https://github.com/Linkurious/linkurious.js/blob/develop/src/renderers/sigma.renderers.canvas.js#L381-L389)

```javascript
        oldHeight = this.height,
        pixelRatio = 1;
        // TODO:
        // *****
        // This pixelRatio is the solution to display with the good definition
        // on canvases on Retina displays (ie oversampling). Unfortunately, it
        // has a huge performance cost...
        //  > pixelRatio = window.devicePixelRatio || 1;
```

![image](https://cloud.githubusercontent.com/assets/1469823/9107855/d0ee730c-3c2a-11e5-9bd4-9a33c1389d31.png)


**feeelss soo gooodd!**

**Comment by sheymann** [comment]
> It has a huge performance cost.

Can you measure and mitigate this cost?

**Comment by mdamien** [comment]
With a first test (xps 13/ubuntu as usual), it goes from `~74.908ms` with current code to `~75.556ms` (reproducible many times)

**Comment by sheymann** [comment]
What is the screen resolution and pixel ratio used for the test?

**Comment by mdamien** [comment]
`2` both for the macbook and the xps

**Comment by jbilcke** [comment]
hey!

I'm just curious, did you test on Chrome or Firefox? 

I wonder if they perform differently for rendering (high density) canvas

**Comment by mdamien** [comment]
Yep, tested on chrome and firefox

**Comment by mdamien** [comment]
Looks like the renderers don't have to be changed:

You can compare the exact same graphs being rendered with or with pixel ratio here:

* master: https://rawgit.com/Linkurious/linkurious.js/master/examples/load-external-gexf.html
* develop: https://rawgit.com/Linkurious/linkurious.js/develop/examples/load-external-gexf.html

Exact same rendering, except for the crispiness of course.

**Comment by mdamien** [comment]
The fix breaks the svg zoom accuracy ( it just zoom at the wrong place ) on hdpi screens.
