### ISSUE TITLE
Remove conrad and batchEdgesDrawing

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#252]
Remove the `batchEdgesDrawing` (buggy and big overhead for nothing). And the `conrad.js` become useless.

* conrad is 1000 lines
* batchEdgesDrawing is something like 100 lines

Underlying goal: Simplify lk.js, make everything more straightforward.

EDIT: Maybe we should no remove it because it can prove useful for usecases with lot of edges and not many nodes.

**Comment by sheymann** [comment]
Need tests

**Comment by sheymann** [comment]
closed as removed in next major release
