### ISSUE TITLE
Tooltips Plugin: adding an "after render" event

### ISSUE THREAD

**Issue by fikipollo** [Linkurious/linkurious.js#253]
Dear devs,

First of all, thanks for your such awesome library and the variety of useful plugins :)

I'm using the Tooltips plugin and I found that would be useful to add a new event just after the tooltip is rendered (i.e. drawn and visible for the user). 

The current "shown" event is fired after the coordinates calculation and the component creation however the *dom* is not rendered yet so I cannot manipulate or work with it.

In my case I just added the following code at **line 293** (*sigma.plugins.tooltips.js* file):
```javascript
self.dispatchEvent('rendered', o);
```

i.e. At function "open", which opens the tooltip, just after the last position corrections (the autoadjust option). 
As you can see I pass **o**, i.e. the node or edge, in my case, it was enough but would be interesting to pass the *event* object that fired the creation of the tooltip.

Hope you find it useful!

Thanks again!!

**Comment by mdamien** [comment]
Hum...this is because `open()` has a `setTimeout(...,0)` to modify the DOM. I think we should consider this as a bug and fire the event at **line 293** like you said. Gonna patch that, @sheymann ok for you ?

**Comment by sheymann** [comment]
Good catch!

@mdamien It's better to add an `onComplete` callback argument to `open()` so that we can fire the `shown` event after the rendering, and apply the same login to `close()`

**Comment by fikipollo** [comment]
Now works perfectly, thank you guys!
