### ISSUE TITLE
renderers.halo: edges drawn behind existing edges and halos

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#259]
I've implemented an overNodes binding on our graph using the code below:
```
s.bind('overNodes', function(e) {
  var adjacentNodes = [],
      adjacentEdges = [];

  // Get adjacent nodes:
  e.data.nodes.forEach(function(node) {
    s.graph.adjacentNodes(node.id).forEach(function(n) {
      adjacentNodes.push(n);
    })
  });

  // Add hovered nodes to the array and remove duplicates:
  adjacentNodes = _.uniq(adjacentNodes.concat(e.data.nodes)); // (using underscore js to create unique array)

  $.each(s.graph.edges(),function(){
    that = this; // re-assign "this" so that we don't screw up later
    $.each(adjacentNodes, function() {
      if (this.id == that.source || this.id == that.target) {
        that.type = 'curvedArrow'; // for some reason, when reading the edge, the type doesn't show up, so I'm adding it to the "that" object.
        adjacentEdges.push(that);
      }
    });
  });

  // Render halo:
  s.renderers[0].halo({
    nodes: adjacentNodes,
    edges: adjacentEdges,
    nodeHaloColor: '#E7ABAA',
    nodeHaloSize: 20,
    edgeHaloColor: '#8C0000',
    edgeHaloSize: 1
  });
});
```
The graph generates properly and hovering over a node does generate a halo and does put a new line in for the edge in the color and size I have in the function above. However, the new line appears behind the original edge, but sometimes just slightly offset so you can see part of it. The new edges also appear behind the halo and not in front so the whole thing looks goofy.

See attached image. The maroon edges are the halo-drawn edges, where the gray ones are the original.
![halo issues](https://cloud.githubusercontent.com/assets/1018133/9450682/f39a6cc0-4a5e-11e5-963b-36581ee3a12a.png)

**Comment by sheymann** [comment]
The `overNodes` event has disappeard from the [latest release](https://github.com/Linkurious/linkurious.js/releases/tag/v1.1.0), please use `hovers` instead.

```js
'hovers', {
  current: {
    nodes: currHoveredNodes,
    edges: currHoveredEdges,
  },
  enter: {
    nodes: newOverNodes,
    edges: newOverEdges,
  },
  leave: {
    nodes: newOutNodes,
    edges: newOutEdges,
  },
  captor: e.data
}
```

ref https://github.com/Linkurious/linkurious.js/issues/213

**Comment by emergingdzns** [comment]
Thanks @sheymann . I updated to the latest build and got the hovers working and realized that the edges were new edges but actual halos on the edges. All good with this now.
