### ISSUE TITLE
ForceAtlas2 no longer accepts autoStop

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#261]
I am perplexed as to why the autoStop option was removed from the forceAtlas2 layout plugin in the latest build. This was rather critical. Now our graphs look terrible! The edges never appear because the nodes are twitchier than a chihuahua on acid.

How are we supposed to know WHEN to stop the layout from jittering? Are we supposed to just pick some arbitrary time and stop at that point? What happens if that time is too short? Is the graph not optimal? This is nuts.

Please tell me there's a way to turn that back on.

**Comment by sheymann** [comment]
Hello, please use forceLink instead. The forceAtlas2 layout is now the original layout from sigma. As we've modified the layout progressively, I wanted to be clear that this is a fork.

ref: https://github.com/Linkurious/linkurious.js/issues/126
