### ISSUE TITLE
Method exposure

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#264]
the `open` method is a member of the tooltips object, so I can override it if I want to like this:

    var tt = sigma.plugins.tooltips(s, s.renderers[0], {node: opts});
    tt.open = function(node) { ... }

as is its corresponding `close`, however, whereas the `open` is called from the method that gets bound to an event, for `close` that's not the case.

```
    this.close = function(e) {
      cancel();
      this.dispatchEvent('hidden', e.data);
      return this;
    };
    s.bind(no.hide, function(event) {
        if (event.data.leave && event.data.leave.nodes.length == 0)
          return
        var p = _tooltip;
        delayedCancel(settings.node.hideDelay);
        if (p)
          self.dispatchEvent('hidden', event.data);
      });
```

which presents a problem for those of us that override those methods.  could we fix this so that the method bound actually does its work using the exposed `close`?

I'm thinking something along the lines of:

```
    this.close = function(e) {
        delayedCancel(settings.node.hideDelay);
        var p = _tooltip;
        if (p)
          self.dispatchEvent('hidden', e.data);
      return this;
    };
    s.bind(no.hide, function(event) {
        if (event.data.leave && event.data.leave.nodes.length == 0)
          return
        self.close(event);
      });
```

**Comment by sheymann** [comment]
I'm not sure to understand what you want to achieve here. Why do you override the methods?

Your suggestion won't work because it would me make impossible to close the tooltip without delay. Also `close` should close the tooltip immediately as it is expected in common UI frameworks like Bootstrap.

**Comment by sheymann** [comment]
closed for inactivity
