### ISSUE TITLE
'minArrowSize' settings not work

### ISSUE THREAD

**Issue by bkkoo** [Linkurious/linkurious.js#266]
Look at the original sigma.js source file 'sigma.canvas.edges.arrow.js' line 27

aSize = Math.max(size * 2.5, settings('minArrowSize'))  // including 'minArrowSize' settings in concern.

but in linkurious source file 'sigma.canvas.edges.arrow.js' line 31

var aSize = size * 2.5     // this does not include 'minArrowSize' settings in concern.

**Comment by sheymann** [comment]
also missing from sigma.canvas.edgehovers.curvedArrow.js and sigma.renderers.linkurious/canvas
