### ISSUE TITLE
Cache text rendering with a buffer for performance

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#271]
Continuing #83, caching text rendering with a buffer for performance seems worth bechmarking to overcome the slowness happening with displaying thousands of text segments. 

A dirty cheching mechanism may be used to refresh the text when node/edge labels change, which can happen by a simple `myNode.label = 'x'`.

**Comment by sheymann** [comment]
@Ytawo can you write down here the test protocol and % of text rendering in a node rendering cycle please?

**Comment by Ytawo** [comment]
Tested with 10.000 nodes with Chrome/Linux.
1) Start a CPU profiling.
2) Play ~10 sec with the graph.

Results:

![screenshot - 05102015 - 10 17 08](https://cloud.githubusercontent.com/assets/1114369/10275846/1017c1c4-6b4b-11e5-9e61-3d7675b82235.png)

~18% for fillText and ~32% for sigma.canvas.label.def (this includes fillText).

Similar results where obtained by "manually" computing the amount of time taken by a graph rendering cycle with and without displaying the node labels.

**Comment by sheymann** [comment]
will be done in next major version
