### ISSUE TITLE
Autosizing

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#279]
I'm using forceLink plugin and when it lays out my nodes, it doesn't pick the closest distances possible from some centre but the farthest, such that there are always nodes on the edge of the screen.  furthermore, when I move a node towards the centre, it zooms the graph such that there are always nodes touching the edges.

I've turned adjustSizes on/off to no avail and see no other options that I could use to change this behaviour. help?

I think, particularly, I'm not as concerned with the initial layout as I am with the fact that the graph auto-resizes.

**Comment by sheymann** [comment]
Node and edge size scaling ratio (regarding the zoom level) can be set to 1, see https://github.com/Linkurious/linkurious.js/wiki/Settings#camera-settings

Is it what you're looking for?

**Comment by ekkis** [comment]
hmm... no.  this is more what I was thinking of: https://github.com/Linkurious/linkurious.js/pull/280 (I don't know how to associate the pull request with this issue)

**Comment by sheymann** [comment]
Closed due to inactivity
