### ISSUE TITLE
Make local indexes more memory-efficient

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious.js#284]
In local indexes:
https://github.com/Linkurious/linkurious.js/blob/develop/src/classes/sigma.classes.graph.js#L70

Minimize key usage by grouping `inNeighborsIndex, outNeighborsIndex, allNeighborsIndex, inNeighborsCount, outNeighborsCount, allNeighborsCount` into  a single `neighborsIndex` containing objects like `{ in:array, out:arry, all:array, inCount:number, outCount:number, allCount:number}`.

**Comment by sheymann** [comment]
- [ ] measure memory usage before and after the patch
- [ ] measure access speed in relevant graph methods

**Comment by davidrapin** [comment]
https://docs.google.com/spreadsheets/d/17Hwg30NVHR7UianXCTo-NlIZY0SU5L5_CaR8dLH49i4/edit#gid=0

Recommendations:
- don't use integers as object keys
- non-integer numbers have poor properties as object keys as well
- concatenating a letter in front of an integer is enough to make `Object.keys` and `for..in` performances go x20.

**Comment by sheymann** [comment]
How about encapsulating indexes to use ES6 Map with a fallback to Object when the browser doesn't support Maps?

**Comment by sheymann** [comment]
code: https://github.com/Linkurious/linkurious.js/tree/284-better-indexes

Tested with examples/load-external-json.html on Chrome, replacing Objects by Maps in graph indexes divides the memory usage by 2 (from 50MB to 25MB)
