### ISSUE TITLE
Incomplete image export on Retina screen

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious.js#285]
In some cases (Chrome on OSX) the generated PNG is incomplete.
This is probably caused by the fact that retina canvases often have too many pixels to render properly.

**Comment by davidrapin** [comment]
@callicles could you provide:
- an example PNG that failed to generate correctly
- chrome version
- screen resolution

**Comment by callicles** [comment]
Here is an example of a failed png,
![882-untitled visualization 2](https://cloud.githubusercontent.com/assets/4429209/10313438/9ed5e6de-6c1d-11e5-9c7a-82347b83ef24.png)

on Version 45.0.2454.101 (64-bit)
Screen: 2880 x 1800 Retina

**Comment by davidrapin** [comment]
@callicles thank you!

**Comment by davidrapin** [comment]
@sheymann ideas?

**Comment by sheymann** [comment]
@callicles I guess you used Linkurious Starter. What is the size of the file that you wanted to export?

**Comment by callicles** [comment]
I used the demo online. If I remember correctly this is using the default parameter.

**Comment by sheymann** [comment]
Does it happen if you change the parameter?

**Comment by callicles** [comment]
same thing
![882-untitled visualization 3](https://cloud.githubusercontent.com/assets/4429209/10325074/d1491124-6c5c-11e5-996e-2ffefff9d989.png)

**Comment by sheymann** [comment]
Does it happen on Firefox as well?

**Comment by callicles** [comment]
![1191-untitled visualization](https://cloud.githubusercontent.com/assets/4429209/10341306/2ce8c436-6ce2-11e5-81c2-ec0c566d0164.png)

**Comment by sheymann** [comment]
This issue appeared after fixing Retina display: #25

**Comment by sheymann** [comment]
How to test on Windows with Firefox:

1. Go to "about:config"
- Find "layout.css.devPixelsPerPx
- Change it to your desired ratio (1 for normal, 2 for retina, etc. -1 seems to be Default.)

**Comment by davidrapin** [comment]
Nice!!

**Comment by sheymann** [comment]
Cannot reproduce on the example, but still buggy in Linkurious products
