### ISSUE TITLE
sigma.statistics.louvain Uncaught RangeError: NaN included. (minimum amount of edges?)

### ISSUE THREAD

**Issue by partizanos** [Linkurious/linkurious.js#286]
In the example of Louvain plugin when the graph contains very few Edges it throws a Range error this is because the level is equal to 0. In a personal project the minimum acceptable is about 20 edges while in the example of the repository (linkurious.js/examples/plugin-louvain.html) when the amount of Edges is set to 1 (for 2-5 it works sometimes I guess it depends on topology two). I haven t checked the python implementation in detail maybe the bug exists there too.

**Comment by partizanos** [comment]
I fixed/patched it like that:

if (level !== undefined && (level < 0 || level > dendogram.length - 1))
 // if (level !== undefined && (level < 1 || level > dendogram.length - 1))

**Comment by sheymann** [comment]
Hi, thanks for spotting the issue. Can you submit a pull request please?

**Comment by partizanos** [comment]
done!

**Comment by sheymann** [comment]
ref https://github.com/Linkurious/linkurious.js/pull/287
