### ISSUE TITLE
Force layout with preferred coords

### ISSUE THREAD

**Issue by antonioaltamura** [Linkurious/linkurious.js#293]
Hi, I want to make a graph with a force positioning algorithm but "preferred" coordinates each node.
After a drag they should come back "smootly" to their preferred coordinates (defined by me).
Not sure it's clear :)

**Comment by sheymann** [comment]
Not really :)

The feature you describe is not a layout, it is a behavior of node dragging. When should the node "come back" at its initial position?

**Comment by alfredopacino** [comment]
I meant "come back" after a dragging action. I know I explained the problem awfully :)
This is was idea:
http://vax.herokuapp.com (you can see the nodes "comes back" to their position after dragging)
But I solved changing the whole concept.
Anyway my 2 cent: this kind of render (forced "smootly") could spread the sigmajs usage and "market" penetration. It's eyecatching and very common, the sigmajs forced plugins doesn't have the same eye-catching factor.

**Comment by sheymann** [comment]
Actually this behavior is already available if you run the layout continuously with reduced speed :)

**Comment by alfredopacino** [comment]
could you post an example of what you talking about?

**Comment by sheymann** [comment]
combine examples/force.html with examples/drag-nodes.html
add `slowDown: 10` or something similar to the settings of the layout, see [settings](https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.layout.forceLink)

**Comment by alfredopacino** [comment]
I'm not sure drag and force plugins are totally "compatible".
Please try to drag a node http://www.filedropper.com/showdownload.php/drag-nodes

**Comment by sheymann** [comment]
The link is broken

**Comment by alfredopacino** [comment]
try this
http://nabbaitalia.it/files/linkurious.js/examples/drag-nodes.html

**Comment by sheymann** [comment]
The force is still to strong and the dragged node is placed again at its optimal position on mouse up.

An alternative is to stop the layout, then code the "way back" behavior manually using the animation plugin: store the node coordinates on `startdrag`, then apply animation on `dragend` events.

**Comment by alfredopacino** [comment]
uhm, using the animation plugin in this way wouldn't make the same "fluctuating" effect..

**Comment by sheymann** [comment]
Closed due to inactivity
