### ISSUE TITLE
Multi-line node labels

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#295]
Add an optional way to split a string into multiple lines to display node labels. An approach is to set a max line size.

- implement on renderers.canvas.linkurious
- deal with hovered nodes the same way

@Ytawo please comment (RFC) :)

**New setting**

- maxNodeLabelLineLength: Maximum length of a node's label (in characters). Displays the label on several lines. 0 disables it (the whole label is displayed on one line).

**Comment by Ytawo** [comment]
I'll take care of that. As you said I suggest we add a setting 'maxNodeLabelLineLength' (the only other way I see is to set it based on the font size or the canvas size, but it doesn't seem very convenient).

**Comment by ekkis** [comment]
so if it's a fixed length in characters, what happens when the boundary falls mid-word? will the word get hyphened or will the algorithm scale back to the nearest word boundary? and what if a word is longer than the limit?

**Comment by sheymann** [comment]
It's not necessay to be very strict as we won't justify the next, so I vote for a nearest word boundary.

**Comment by ekkis** [comment]
agreed.  we just have to account for long words

**Comment by Ytawo** [comment]
So:
* At least one work per line (even if its length is larger than the maximum length of a line)
* Does not "split" words over two lines.

**Comment by sheymann** [comment]
Measuring text length in pixel is a costly operation and I'd prefer that we avoid it. We have recently added a boolean setting called `approximateLabelWidth` to avoid using `canvas.measureText()` at all.

Let's measure line length as the number of characters. The idea of the feature is to cut very long texts, e.g. a paragraph split into lines of 60 chars.

**Comment by Ytawo** [comment]
Ok, settings('maxNodeLabelLineLength') will refer to the maximum number of characters of a line. Default value = 60? Or default value = no split?

**Comment by sheymann** [comment]
default: 0 (feature turned off by default to avoid perf loss)

**Comment by Ytawo** [comment]
See file 'examples/node-labels.html'.

**Comment by ekkis** [comment]
one other thought: if a single word exceeds the length limit, it should be truncated with an ellipsis e.g. with a word length of 8, "serendipity" should read: "seren..."

**Comment by Ytawo** [comment]
Instead of that, I suggest it should be splited over two (or more) lines, with a '-' character.
Example (still with a 8 characters limit): "subdermatoglyphic" -> "subderm-", "atoglyp-", "hic" over 3 lines.

**Comment by sheymann** [comment]
- [ ] @Ytawo can you add this feature to sigma.renderers.linkurious as well? The plugin overrides the default label renderer.

**Comment by sheymann** [comment]
good

**Comment by sheymann** [comment]
Re-open because the `maxNodeLabelLineLength` setting should be used at the "maximum" line length only if there is more an 1 line in a node label. Nodes labels may have different lengths.
