### ISSUE TITLE
better github url

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#298]
I'd just like to suggest that on the home page the instructions for pulling the project from github would be better anonymous.  this:

    git clone git://github.com/Linkurious/linkurious.js.git

instead of this:

    git clone git@github.com:Linkurious/linkurious.js.git

as the former does not require an account to be configured for access.  this is more useful for those who build images so that SSH keys don't have to be registered with github

**Comment by sheymann** [comment]
The issue with anonymous cloning is that potential contributors would need to clone the repo again to submit PR. I prefer to reduce frictions to contribution first.

**Comment by ekkis** [comment]
I understand.  perhaps you could have both urls?  for people like me who are not so savvy with github and just want to install the library the first form is more useful.  if I'm a developer and I know I may contribute, the second form is more appropriate, but if both are on the page then at least I can choose

**Comment by sheymann** [comment]
okay let's submit a PR
