### ISSUE TITLE
Grunt warning when building

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#299]
when I run `npm install` I get the following warning:

> npm WARN engine grunt-grunt@0.2.4: 
> wanted: {"node":"0.10.18","npm":"1.2.x"} (current: {"node":"0.10.29","npm":"1.4.21"})

which is puzzling.  it wants an earlier version?

**Comment by sheymann** [comment]
Your version of node is too old, please upgrade to 0.12 or v4

**Comment by ekkis** [comment]
I get that when running the build from a Dockerfile for an image based on the latest node.js.  if I type `node --version` after the image is built I get v0.10.40. 

additionally, notice that the "current" is indicated as 0.10.40 but the linkurious software seems to want an older version 0.10.18... and this is from a fresh fetch from github

> npm WARN engine grunt-grunt@0.2.4: wanted: {"node":"0.10.18","npm":"1.2.x"} (current: {"node":"0.10.40","npm":"2.14.1"})

**Comment by sheymann** [comment]
We should update the dependencies

**Comment by sheymann** [comment]
There is no more recent version of grunt-grunt@0.2.4

**Comment by ekkis** [comment]
it's not complaining about the version of grunt.  it's the versions of node and npm the library currently requires.  if you read the warning carefully you'll notice that I have a later version than that required.  the library needs fixing.

**Comment by sheymann** [comment]
feel free to submit a patch to https://github.com/bevacqua/grunt-grunt because the warning comes from this dependency.
