### ISSUE TITLE
enable node border only on hover

### ISSUE THREAD

**Issue by gfgqtmakia** [Linkurious/linkurious.js#301]
I'm not able to create nodes that has border only on hover.

**Comment by sheymann** [comment]
Hi, this behavior is not available anymore since release v1.2.0.

**Comment by gfgqtmakia** [comment]
hi, so it is not specified in the wiki how to set border color, hover
border color and active border color.
how can i do this?
בתאריך 28 באוק 2015 13:08,‏ "Sébastien Heymann" <notifications@github.com>
כתב:

**Comment by sheymann** [comment]
It is possible to set border color and border size, see https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.renderers.linkurious

**Comment by gfgqtmakia** [comment]
Thank you!
בתאריך 28 באוק 2015 14:57,‏ "Sébastien Heymann" <notifications@github.com>
כתב:

**Comment by gfgqtmakia** [comment]
also,
* is it possible to apply a layout only on sub graph? (let's say only on
active nodes)
* how can i zoom only on a sub graph (like camera reset, but to show in the
frame only selected nodes)
* why are all the layouts makes you use the whole frame? the distance
between nodes is too big. maybe it is customizable via avgDistanceThreshold
in forceLink? it is not well documented what every setting does in the
layout

thank you.
בתאריך 28 באוק 2015 15:41,‏ "gfgqtmakia" <gfgqtmakia@gmail.com> כתב:

**Comment by sheymann** [comment]
* is it possible to apply a layout only on sub graph? (let's say only on
active nodes)

No

* how can i zoom only on a sub graph (like camera reset, but to show in the
frame only selected nodes)

Use plugins.locate

* why are all the layouts makes you use the whole frame? the distance
between nodes is too big. maybe it is customizable via avgDistanceThreshold
in forceLink? it is not well documented what every setting does in the
layout

It depends on other settings in sigma, be sure to set sigma `autoRescale` to `false`.

To learn more about the settings in forceLink, I recommend to read [this paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679).

**Comment by gfgqtmakia** [comment]
Thank you, you were very helpful. have a nice weekend.  :-)
בתאריך 13 בנוב 2015 13:00,‏ "Sébastien Heymann" <notifications@github.com>
כתב:

**Comment by sheymann** [comment]
You're welcome!
