### ISSUE TITLE
autoCurve no longer accepts options.  ouch.

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#302]
in my original implementation of autoCurve (now sigma.canvas.edges.autoCurve.js) I could pass an options parameter where I could specify the calculation and step functions, the type of arrow to use, and other values.  the current version of this module hard-codes specific behaviour, and robs the caller of choice for no reason.

is there an issue of policy here, or could we have the flexibility I originally built into this functionality?

p.s. it means that at present I can't grab the code from github for a docker image I'm building for the library because it breaks my code

**Comment by sheymann** [comment]
Your implementation was very buggy and couldn't fix it, so I decided to remove the option. Please feel free to submit a patch, and please test it with a lot of values (e.g. value different that the default x would cause weird drawing of edges)

**Comment by ekkis** [comment]
https://github.com/ekkis/linkurious.js/pull/1 - I didn't want to merge it because I gather you have a test suite you'll want to run so I leave that exercise to you
