### ISSUE TITLE
Announcement: Docker image for Linkurious library

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#304]
I've taken the trouble to containerise the library.  not sure where it's appropriate to make this announcement so I'm creating it as an "issue".

see here: https://hub.docker.com/r/ekkis/linkurious.js/

**Comment by sheymann** [comment]
Awesome! Can you edit the short description from "Running Linkurious applications..." to "Running applications built with linkurious.js" to avoid confusion with Linkurious Enterprise?

**Comment by ekkis** [comment]
done
