### ISSUE TITLE
autoResize option has no effect

### ISSUE THREAD

**Issue by Mythli** [Linkurious/linkurious.js#305]
The documentation is hinting that with the option autoResize set to false the graph does not resize on its own anymore.

The option is not used at all in the code and therefore should be removed from the wiki or implemented in the code base.

To reproduce this issue simply set autoResize to false and see the graph resizing or search for autoResize in the codebase. You will only finde the config entry- no mention in the code

Btw:
I want to trigger resizing manually ( thats why i looked in the source for what is done when automaticly resizing) How would I do this ( avoiding such stuff: $(window).trigger('resize'); ).

Best Regards

**Comment by sheymann** [comment]
Actually the autoResize works by default whatever the setting value, see code here:

https://github.com/Linkurious/linkurious.js/search?utf8=%E2%9C%93&q=resize

Thanks for it, I've removed the setting.
