### ISSUE TITLE
Grouping the nodes after loading the graph from neo4j

### ISSUE THREAD

**Issue by yohanjoseph** [Linkurious/linkurious.js#312]
I'm doing a demo on graph visualization and i've stored the database on neo4j and visualized it using sigma js. Now the issue is, sigma js renders the graph in a random manner each time which will not be useful to the end user. So what i want to do is render it in a orderly fashion like, placing a center node and putting all the related nodes around it which has a connection with it. Any help is much appreciated. :)

**Comment by sheymann** [comment]
Hello, the radial layout is under development by @Ytawo

**Comment by yohanjoseph** [comment]
This is the type of layout i'm looking for. Any update on the same ?

![capture](https://cloud.githubusercontent.com/assets/15865529/11293453/3e533f92-8f80-11e5-8bb2-305ff7117af7.PNG)

**Comment by sheymann** [comment]
implemented in next major release
