### ISSUE TITLE
Question: ng-show resize graph

### ISSUE THREAD

**Issue by ikwattro** [Linkurious/linkurious.js#313]
Hi guys,

I'm currently integrating linkurious.js in Graphgen.

I'm using ng-show on the graph container. However, even by calling `sigma.renderers[0].resize()` after the ng-show condition is true, the canvas stays at 0px x 0px.

Do you have an idea on how to force resize the canvas ?

![screen shot 2015-11-16 at 16 08 10](https://cloud.githubusercontent.com/assets/1222009/11186173/bc1f1246-8c80-11e5-8179-da8dae2772a5.png)

Cheers !

**Comment by sheymann** [comment]
Yup, `ng-show` toggles the CSS property `display` to true or false, and has nothing to do with a resize. It's better to instanciate linkurious.js once the div container has a size.

**Comment by ikwattro** [comment]
Thanks, I tried to : 

1. set ng-show first to true
2. instantiate sigma with an empty graph
3. set ng-show to false

Until now, the canvas has the desired width and height, even with the `hidden` attr.

4. set ng-show to true
5. add nodes and edges
6. refresh sigma

After 6, my canvas is again at 0px x 0px .

I'm wondering if it would not be better to kill the sigma instances after each generation and create a new one.

**Comment by ikwattro** [comment]
Ok, If I add a timeout of 1ms between ng-show and the sigma instantiation, it is working fine. Thanks !

**Comment by sheymann** [comment]
A better solution would be to have `vm.hasGraph` as a boolean, and that boolean is set by the code responsible for instanciating sigma. Timeouts are evil :)

**Comment by ikwattro** [comment]
Well this returns a boolean. Here is my directive controller : 

```
/** @ngInject */
        function LinkuriousController($rootScope, gaGenerator, graphService, $timeout){
            var vm = this;
            vm._hasGraph = false;
            vm.hasGraph = hasGraph;

            function hasGraph(){
                return vm._hasGraph;
            }


            $rootScope.$on('generation-complete', function(e) {
                vm._hasGraph = true;
                $timeout(function(){
                    buildGraph();
                }, 1);
            });

            function buildGraph() {
                graphService.init();
                var data = gaGenerator.getData();
                angular.forEach(data.nodes, function(n){
                    graphService.addNode({
                        id: n._id,
                        label: n.labels[0],
                        x: Math.random(),
                        y: Math.random(),
                        size: 15
                    });
                });
                angular.forEach(data.edges, function(e, k) {
                    graphService.addEdge({
                        id: k,
                        source: e._source,
                        target: e._target
                    });
                });
                graphService.refresh();
            }
        }
```

**Comment by ikwattro** [comment]
Or should I watch for the `vm._hasGraph` property inside the controller ?

**Comment by sheymann** [comment]
You can simply use: `ng-show="vm._hasGraph"`

**Comment by sheymann** [comment]
Angular will internally add a watcher on this property. Boolean watchers are very cheap so don't worry about it.

**Comment by ikwattro** [comment]
Yes, but this doesn't solve the canvas size :( 

```
/** @ngInject */
        function LinkuriousController($rootScope, gaGenerator, graphService, $timeout){
            var vm = this;
            vm._hasGraph = false;


            $rootScope.$on('generation-complete', function(e) {
                vm._hasGraph = true;
                buildGraph();
            });
```

**Comment by sheymann** [comment]
Ah I see. How about setting a width/height to the linkurious container in any case?

**Comment by ikwattro** [comment]
You mean in the html or via the config ?

**Comment by sheymann** [comment]
In the CSS

**Comment by ikwattro** [comment]
There is a fixed width and height for the graph container in the css, I'll try to make a fiddle to append here

Envoyé de mon iPhone

**Comment by ikwattro** [comment]
Here it is : https://jsfiddle.net/HB7LU/19942/
