### ISSUE TITLE
DragNodes Plugin - Suggested Fix

### ISSUE THREAD

**Issue by apitts** [Linkurious/linkurious.js#317]
With the updated hovers event it would be simpler to use the hoverStack rather than recreate the functionality in the dragNodes plugin, i.e. use the below directly in the plugin:
```javascript
_hoverStack = event.data.current.nodes;
```

This would also fix a minor bug as it seems that the plugin and the hovers event treat the hoverStack slightly differently which sometimes causes a mismatch in the hovered node and the dragged node if there is overlap.

The history is I believe that the hoverStack in dragNodes was created prior to the hovers event and its associated hoverStack. 

Let me know if you would like a pull request.

**Comment by sheymann** [comment]
I disagree: dragging a single node, even when multiple nodes overlap, makes it easy to untangle the graph.

To hover a single node, set `singleHover` to `true` in sigma settings.

**Comment by apitts** [comment]
I think you misunderstand me. You would still be able to drag a single node, it's just about the creation of the hoverStack. Don't recreate it in the plugin but rather use the hoverStack in the hovers event.

**Comment by sheymann** [comment]
The thing is that the sigma renderer doesn't use a hover stack. It's sole purpose is for the dragNodes.

**Comment by apitts** [comment]
Yes, apologies for the confusion regarding the name. I think of data.current.nodes as the 'hoverStack' in the hovers event. My point is only that it would be easier to use data.current.nodes rather than create and maintain the hoverStack in the dragNodes plugin as is currently done. They are essentially the same thing...it's just that data.current.nodes didn't exist when the dragNodes plugin was originally written. And, as a consequence, we have a double up that leads to issues if you are using the hovers event elsewhere...at least for me. No problem if you wan to leave as is until and unless you encounter an issue...just letting you know about it.

**Comment by sheymann** [comment]
Alright, at the moment I prefer to keep these things isolated.
