### ISSUE TITLE
Dagre plugin - suggested improvement

### ISSUE THREAD

**Issue by apitts** [Linkurious/linkurious.js#318]
Currently the layout does not add fixed nodes, it would be nice if it also excluded hidden nodes. That is to say use the below:
```javascript
if (!nodes[i].fixed && !nodes[i].hidden) {
    dg.setNode(nodes[i].id, {});
}
```

Please let me know if you agree and, if so, whether you would like a pull request.

**Comment by sheymann** [comment]
It's not always a desired feature: you may hide nodes based on a live filtering system, and here it's better to have stable node positions instead of re-layouting each time the filter changes.

This could be an option of the layout though, feel free to submit a PR.

**Comment by apitts** [comment]
Fair enough. I'll leave as is for the moment to avoid adding too many settings unless anyone else comments here looking for it.
