### ISSUE TITLE
Angular Example

### ISSUE THREAD

**Issue by kiro112** [Linkurious/linkurious.js#323]
is there a running example/repo of linkurious for angularjs ?

thanks

**Comment by sheymann** [comment]
No because the integration depends on the architecture of your project.

**Comment by kiro112** [comment]
@sheymann  is there any change that you can provide example usage for angular 1.x.x (regardless of architecture ) ?

i think examples with be a really great help

**Comment by sheymann** [comment]
No, this is explained in the wiki page: https://github.com/Linkurious/linkurious.js/wiki/How-to-integrate-with-Angular.js

**Comment by kiro112** [comment]
ok, thanks @sheymann
