### ISSUE TITLE
Regression: slow camera

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#342]
https://github.com/Linkurious/linkurious.js/commit/69c982c55abc82d50bfcd38e61e35f1122ace735 introduces a regression because requestAnimationFrame should be cancelled if an frame is currently rendered.

**Comment by sheymann** [comment]
@mdamien grrr :hamster:

**Comment by sheymann** [comment]
x10 perfs

**Comment by mdamien** [comment]
@sheymann I see, the important part was that I removed this while doing a refactor of the function:

```
this.cameraFrames[camera.id] = requestAnimationFrame(function() {
  delete self.cameraFrames[camera.id];
});
```

Lesson of the day: keep the refactor and the perf fixes in different commits.

**Comment by sheymann** [comment]
Yup, btw are you back from the Bay?

**Comment by mdamien** [comment]
Yep, just got back ! Now I need to see the new office of Linkurious ! :smile:

**Comment by sheymann** [comment]
Hehe when you want, it rocks!
