### ISSUE TITLE
add ponderation on edges to perform bellmanford pathfinding

### ISSUE THREAD

**Issue by lastnod** [Linkurious/linkurious.js#344]
Add ponderation on edged to perform bellmanford pathfinding

**Comment by sheymann** [comment]
`edge.weight` can be used, or might be better to give a parameter to the algorithm to get the right edge property

**Comment by lastnod** [comment]
Exemple i want to know the best price for the minor ris. Here it's a simple example but it can be reeealy more tricky. some times the lower price  is not the less risky situation.

![image](https://cloud.githubusercontent.com/assets/8791187/13332962/af697fa4-dc04-11e5-8d15-a124553855a6.png)

**Comment by sheymann** [comment]
Duplicate of #15
