### ISSUE TITLE
ForceLink Layout pull nodes too close together

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious.js#351]
Happens when parallel edges with more than 3 edges. 
Implementing a minimum node distance would be nice.

**Comment by davidrapin** [comment]
@sheymann review plz

**Comment by sheymann** [comment]
The default value should be 0. Current default value breaks examples/force-background.html

**Comment by davidrapin** [comment]
@sheymann fixed :)

**Comment by sheymann** [comment]
ok
