### ISSUE TITLE
plugin:design.js error on line 936

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#352]
With each of the last few updates from Linkurious, I've had to edit the sigma.plugins.design.js file as it always throws this error at me:
`Cannot create property 'active' on string 'line'`

With each version the line number is different, but with the latest version it's on line 936. It's in this set of code:
```
function __apply(mappings, vision, visualVar) {
  if (!visualVar) {
	// apply all styles if no visual variable is specified:
	Object.keys(mappings).forEach(function (visuVar) {
	  mappings[visuVar].active = false; // <============== this is the error line
	  if (mappings[visuVar] && mappings[visuVar].by) {
		vision.applyStyle(visuVar, mappings[visuVar].by);
		mappings[visuVar].active = true;
	  }
	});
  }
  else if (mappings[visualVar] && mappings[visualVar].by) {
	// apply the style of the specified visual variable:
	vision.applyStyle(visualVar, mappings[visualVar].by);
	mappings[visualVar].active = true;
  }

  if (s) s.refresh({skipIndexation: true});
};
```

The only way it seems there is to fix it is to comment out that line. Everything works perfect after that. I haven't been able to deduce what is causing it though and I'd really like to avoid modifying the library code in the future. Any thoughts on what could cause that error?

**Comment by sheymann** [comment]
Hello,

Can you [export the styles](https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.plugins.design#export-styles-and-palette) and copy the content here please?

**Comment by sheymann** [comment]
Closed due to inactivity
