### ISSUE TITLE
Retina export broken on latest version

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#353]
After having just upgraded to the latest, when we try to export the graph image on a retina display, it comes out cropped to the top left quarter of the graph.

Example attached.

![graph 2](https://cloud.githubusercontent.com/assets/1018133/13831134/939d0950-eb8e-11e5-923a-87c0028d52e7.png)

Also, in Safari, when exporting the image it still just opens the image as a png data block without forcing a download. Any fix for that?

**Comment by sheymann** [comment]
Hello,

Does the first bug happens with the previous version? Which version?

**Comment by emergingdzns** [comment]
No it was working fine in the previous version of linkurious. But honestly I can't figure out what version it was. Where do I find the actual version number? I still have our previous code set so I can check it, but it seems like there's a ton of different version numbers in the various files.

**Comment by emergingdzns** [comment]
The last time I updated the linkurious library was Aug 25, 2015, so whatever version was current at that time is the previous version and it worked fine there (first bug).

I think the second bug has been an issue for a long time, but I think it's because Safari sucks.

**Comment by emergingdzns** [comment]
Ok so as I'm trying to build a jsbin for this so I can share just the important stuff with you I realized that in the code of the page where I'm doing the generate on the image, it's referring to `sigma.plugins.image(...)` instead of `sigma.exporters.image(...)` which is stated in the documentation on this page: https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.exporters.image.

However, when I change it to exporters from plugins and try, I just get an error:
> Uncaught TypeError: Cannot read property 'image' of undefined

I checked and made sure that the page is loading plugins/sigma.exporters.image/sigma.exporters.image.js.

So I checked your example linked from the above document and it says so use sigma.plugins.image. I then went to the main github page for linkurious and I saw the "Plugins" link (https://rawgit.com/Linkurious/linkurious.js/develop/plugins/list.html). I follow that link and in the list on the left of plugins, exporters.image doesn't show up but plugins.image does.

So now I'm really confused. Please provide some guidance here. Which is correct? `exporters.image` or `plugins.image`? Seems pointless to spend the time putting together an example if I'm not even sure which code I'm supposed to be using.

FYI, I also tried using the sigma.plugins.image from the previous version (having html load this file instead) and left the js calling `sigma.plugins.image(...)` and it still gives the top left quarter of the graph on retina displays. That same plugin worked fine on the last version of the linkurious/sigma system, so I think something changed in the core regarding retina displays.

**Comment by emergingdzns** [comment]
Just to finish up what I started, I created a gist here: https://gist.github.com/anonymous/7f50e4845bf5100e73ff

I can't run it in jsbin or fiddle or anything because I don't have an https enabled hosting system where I can put the linkurious files. But this is at least some info that might help.

**Comment by sheymann** [comment]
duplicate of #285

**Comment by emergingdzns** [comment]
#285 is still showing as an open issue from 6 months ago. It was working fine in the version of linkurious from August of 2015.

**Comment by emergingdzns** [comment]
I retract my previous statement.... It was not in fact fixed on the previous built. I was mistaken. So this is in fact an open issue. I'll close this thread out in favor of #285.

**Comment by sheymann** [comment]
@emergingdzns thanks, I've found a fix! You can try it on `develop` before the next release.
