### ISSUE TITLE
plugin: noverlap labels

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#355]
We have implemented the noverlap layout plugin. It works great for the nodes themselves, but the labels still overlap. See the image here:

![image](https://cloud.githubusercontent.com/assets/1018133/13934213/23960182-ef6e-11e5-9e83-2521d3e770f3.png)

Is there a way to have it include the area of the label when shifting the nodes around to avoid overlap?

**Comment by sheymann** [comment]
As far as I know this algorithm, it was not designed to handle shapes and thus to include text areas.

How about displaying text at the center of nodes?

**Comment by emergingdzns** [comment]
Yeah we tried that but it's hard to read the labels that way. Boss wants it to the right.

**Comment by emergingdzns** [comment]
I wonder if @apitts has any ideas on this.

**Comment by apitts** [comment]
I am afraid the algorithm does not support that and it would not be
straightforward to add. It's an interesting idea though.

**Comment by sheymann** [comment]
A workaround is to display at most one overlapping label. Users would then never see labels that overlap. They may zoom in to display more labels thought. We've implemented that solution for the next major release.
