### ISSUE TITLE
plugins.legend: Uncaught TypeError: Cannot read property 'widgets' of undefined

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#356]
@Ytawo what would be the cause of the following exception?

>sigma.plugins.legend.js:335 Uncaught TypeError: Cannot read property 'widgets' of undefined

> (anonymous function)	@	sigma.plugins.legend.js:335
(anonymous function)	@	sigma.plugins.legend.js:334
h	@	sigma.plugins.legend.js:196
m	@	sigma.plugins.legend.js:318
(anonymous function)	@	sigma.plugins.legend.js:1293
(anonymous function)	@	sigma.plugins.legend.js:287

**Comment by Ytawo** [comment]
Do you have a way to reproduce it?

**Comment by Ytawo** [comment]
Fixed: it failed when the file was minified. The parent element's width was 0, setting the number of available columns to display the legend to 0.

I did a dirty fix: when the plugin is initialized, it checks the width of the parent element:

* if it is 0, it setTimeout the initialization
* if it is not 0, it computes the legend layout

**Comment by sheymann** [comment]
ok
