### ISSUE TITLE
Tooltip: allow click inside tooltip

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#357]
We have a nice network graph going and we have attached tooltips to the nodes. Right now the show up when you click on the node. But then, no matter where you click (on the tooltip or not) the tooltip disappears. I'd really like to make it so that the tooltip doesn't go away if you click on anything inside the tooltip. Any ideas?

**Comment by sheymann** [comment]
What is the configuration of the tooltip plugin?

You can set the `hide` key to choose the sigma event that will close the tooltip: https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.plugins.tooltips

Also the tooltip should not hide when clicking inside it. The only technical reason would be that the pointer events hits the sigma container.

**Comment by emergingdzns** [comment]
Thanks @sheymann. While your suggestions were the actual answer, they led to me discovering the problem. :-).
