### ISSUE TITLE
Archive `linkurious.js-1.5.0.zip` does not contain the latest version of Sigma.js (1.5)

### ISSUE THREAD

**Issue by NiklasA** [Linkurious/linkurious.js#359]
Hey,

in the last few days we had some trouble with Linkurious.js. We could not create Tooltips with mutiple nodes. By chance we found the issue yesterday. We used your Releases package (v.1.5.0 Source code (zip)). In this archive in the **dist** directory the sigma.js version is not up to date (version 1.3 is included instead of 1.5). After we used the sigma / plugin files from your [GitHub Repo](https://github.com/Linkurious/linkurious.js/tree/develop/dist), everything worked fine for us. Could you please update the current Release ZIP archive?

Thank you in advance.
Niklas

**Comment by sheymann** [comment]
Sorry about that! I've published v1.5.1: https://github.com/Linkurious/linkurious.js/releases/tag/v1.5.1

Best,
Seb

**Comment by NiklasA** [comment]
Thank you!
