### ISSUE TITLE
Using forceLink layout with webpack

### ISSUE THREAD

**Issue by samechikson** [Linkurious/linkurious.js#360]
Hi, I'm trying to load sigma and linkurious plugins through webpack, but am running into issues when loading the sigma.layout.forceLink plugin. Below is what my requires look like 
```javascript
window.sigma = require('sigma');
require("sigma/plugins/sigma.plugins.dragNodes/sigma.plugins.dragNodes.js");
require("sigma/plugins/sigma.plugins.select/sigma.plugins.select.js");
require("sigma/plugins/sigma.plugins.keyboard/sigma.plugins.keyboard.js");
require("sigma/plugins/sigma.plugins.selection/sigma.plugins.selection.js");
require("sigma/plugins/sigma.layouts.forceLink/worker.js");
require("sigma/plugins/sigma.layouts.forceLink/supervisor.js");
```
And my error being 
```
angular.js:12477 TypeError: sigma.layouts.getForceLinkWorker is not a function
    at Supervisor.initWorker (supervisor.js:196)
    at new Supervisor (supervisor.js:62)
    at Object.sigma.layouts.startForceLink (supervisor.js:345)
    at Object.init (force_atlas_config_service.js:33)
    at Scope.scope.refreshGraph (sigma_directive.js:243)
    at Object.scope.updateConfiguration (sigma_directive.js:104)
    at Object.mediator.dispatch (mediator.js:22)
    at Object.fn (graph_config.js:34)
    at Scope.$digest (angular.js:15826)
    at Scope.$apply (angular.js:16097)
```
I've gathered that there's something wrong with the this context not being what it's supposed to be from this [link](https://gitter.im/Linkurious/linkurious.js/archives/2015/09/17), but I am not sure how to fix this. Is there a way I can apply the global scope onto the Worker ? This only seems to be an issue when loading with webpack though, so is there any plan to make this plugin compatible?

**Comment by samechikson** [comment]
I was able to remove the errors by calling the iife function for both the worker.js and the supervisor.js with the `window` object instead of `this`. I guess it makes sense if webpack somehow executes the files within a different context than window. But with my limited knowledge of how webpack bundles work, I am not sure... My question still stands though, is there any plan to make these plugins webpack compatible? Sigma is compatible, so should the plugins be as well? Thanks.

Anyway, perhaps this issue can save someone a few minutes (or hours...) of debugging!

**Comment by sheymann** [comment]
Thanks for pointing this issue! We currently work on a better packaging of the library, stay tuned :)

**Comment by zakjan** [comment]
@sheymann Any progress? I have the same issue with JSPM.

**Comment by sheymann** [comment]
The next major release is planned for this automn. It's a complete re-development from zero.
