### ISSUE TITLE
Gruntfile and the distribution folder

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#361]
there is a `dist/` folder in the the source, which presumably gets written to as a function of a grunt task but I've looked through the `Gruntfile.js` and see nothing responsible.  I've made a change to the code and have rebuilt, now I want to regenerate the contents of the distribution folder.  how do I do it?

**Comment by sheymann** [comment]
Hi, the `dist/` folder contains the latest release, so you should not edit its content.
