### ISSUE TITLE
requiring from node.js

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#362]
the `Gruntfile.js` creates the `build/sigma.require.js` by concatenating all the core files.  it places the `sigma.export.js` in third place, behind core and conrad, because it exports those values and thus they need to be defined first.

however, when requiring linkurious from a node.js application, the code fails because the first thing `sigma.core.js` does is call `window.addEventListener()` and `window` doesn't exist.  this problem is remediated by `sigma.export.js` but too late.

so we can't move the export file to the top because `sigma` and `conrad` won't yet have been defined and I'm not sure moving the remediation in the export file:

    if (typeof window === 'undefined')
      window = {
        addEventListener: function() {}
      };

to the core file makes sense because the absence of `window` is a node.js issue and thus should be in the export file.  thoughts as to the correct approach?

**Comment by sheymann** [comment]
merged, thanks!
