### ISSUE TITLE
Click to focus feature

### ISSUE THREAD

**Issue by Ytawo** [Linkurious/linkurious.js#369]
Added a global setting 'clickToFocus'.

By default, the DOM container loses the focus when the mouse leaves it.

If `clickToFocus` is true, the user has to click on the container to focus it. If it is false, the container is focused when the mouse enters it.

**Comment by sheymann** [comment]
also removes the 'autofocus' setting of plugins.keyboard

**Comment by Ytawo** [comment]
I removed it at the same time.

**Comment by sheymann** [comment]
ok
