### ISSUE TITLE
does activeState support multiple instances?

### ISSUE THREAD

**Issue by tmoerman** [Linkurious/linkurious.js#370]
In the wiki page https://github.com/Linkurious/linkurious.js/wiki/Multi-instance-support is stated that activeState supports multiple (Sigma?) instances.

Is this really the case? I would guess only one instance of ActiveState is maintained at the plugin level:

```JavaScript
/**
   * @param {sigma} s The sigma instance.
   */
  sigma.plugins.activeState = function(s) {
    // Create object if undefined
    if (!_instance) {
      _instance = new ActiveState(s);
    }
    return _instance;
  };

  /**
   *  This function kills the activeState instance.
   */
  sigma.plugins.killActiveState = function() {
    if (_instance instanceof ActiveState) {
      _instance.kill();
      _instance = null;
    }
  };
```

Thx.

**Comment by sheymann** [comment]
You're correct, it doesn't. Can you provide a PR please?

See https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.plugins.select/sigma.plugins.select.js#L377 for an example.

**Comment by sheymann** [comment]
fixed in next major release
