### ISSUE TITLE
Filter Plugin adjacentNodes/Edges not updated to use sigma.util.map

### ISSUE THREAD

**Issue by rerobins** [Linkurious/linkurious.js#371]
If `sigma.plugins.filter` is loaded before `sigma.helpers.graph`, `adjacentNodes` will no longer work.  This is due to `sigma.plugins.filter` using the old object based map system for implementing index look ups.  

I would like to see `sigma.plugins.filter` require `sigma.helpers.graph`, so that the code doesn't have to be maintained twice and this issue comes up again.  Otherwise the code from the  `sigma.helpers.graph` plugin needs to be copied and pasted into the `sigma.plugins.filter`.  

This affects both `adjacentNodes` and `adjacentEdges` methods.

I would submit a merge request for this, but I don't know which method you want to use to solve the problem.

**Comment by sheymann** [comment]
Can you provide a sample on how to reproduce the issue? I recommend to package the library and plugins within a single file, see Gruntfile.js.

**Comment by rerobins** [comment]
I can provide an example if you really want, but this should explain the issue:

`adjacentNodes`:
[This Method](https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.helpers.graph/sigma.helpers.graph.js#L171) should provide the same functionality as [This Method](https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.plugins.filter/sigma.plugins.filter.js#L21).

`adjacentEdges`:
[This Method](https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.helpers.graph/sigma.helpers.graph.js#L218) should provide the same functionality as [This Method](https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.plugins.filter/sigma.plugins.filter.js#L40).  

The difference is that the code should use `indexMap.get(id)` instead of `indexMap[id]`.
