### ISSUE TITLE
Sigma.js : Assocaiative Color and Icon properties of new nodes not shown in graph

### ISSUE THREAD

**Issue by zohairzohair4** [Linkurious/linkurious.js#373]
I got an example code from http://localhost:8000/examples/. And starting building my own. The problem that I am facing is that I have JSON of nodes from neo4j graph DB. that I want to add. I am succesful in adding it but the Icon and Color associated with the noe4j_labels are not represented in the graph.

Sigma Design Plugin is being used
`var graphStyles = {
        nodes: {
            icon: {
                by: 'neo4j_labels',
                scheme: 'nodeIconScheme',
            },
            color: {
                by: 'neo4j_labels',
                scheme: 'nodeColorScheme',
            },
        }
    }

// Instanciate the design:
var design = sigma.plugins.design(s, {
    styles: graphStyles,
    palette: graphPalettes
}`

The nodes that are added from the first query are represented properly with their respective Icons and Colors.
`sigma.neo4j.cypher(
                { url: 'http://localhost:7474', user: 'neo4j', password: 'neo' },
                query_init,
                s,
                function(s) {`

But when I try to add new nodes `s.graph.addNode(new_graph_vars[0]);`
I run into this problem.

**Comment by sheymann** [comment]
Hello, do you call `sigma.refresh()` after `s.graph.addNode()`?

**Comment by sheymann** [comment]
Otherwise the main reason is that the design plus is **lazy** as stated in the documentation, so you must deprecate styles with `design.deprecate();` then call `design.apply('nodes');` to apply. Call these function after adding all nodes because they are expensive.

Refs: https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.plugins.design

**Comment by sheymann** [comment]
Closed due to inactivity
