### ISSUE TITLE
Legend Needs Resize functionality

### ISSUE THREAD

**Issue by rerobins** [Linkurious/linkurious.js#374]
Currently when the window resizes, the legend will listen for that event and recalculate the size of the canvas in order to place the widgets in place.  There is currently now way for that functionality to take place without a window resize.

For example, I'm using Linkurious and angular-resizable in order to change the size of the panel that renders linkurious.  I can refresh the size of linkurious by calling `sigmaInstance.refresh()` , but the legend will not be repositioned, because it doesn't have the functionality to recalculate the positions on the drawing canvas.

I recommend creating a reset() or reposition() method that will provide the following functionality:

```javascript
LegendPlugin.prototype.reset = function(callback) {
    var pixelRatio = this._visualSettings.pixelRatio;
    setupCanvas(this._canvas, this.renderer.container.offsetWidth, 
                this.renderer.container.offsetHeight, pixelRatio);
    this.draw(callback);
  };
```

**Comment by sheymann** [comment]
@Ytawo is it fixed in Ogma?

**Comment by Ytawo** [comment]
Yes! There is a `redraw` method.
