### ISSUE TITLE
Cannot use same icon for two different legend items

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#376]
> I use sigma.plugins.design to apply font icon to nodes and sigma.plugins.legend to render a legend. Some icons are purposely duplicate, i.e. the same icon for two different legend items. The issue I have found is that legend plugin doesn’t support this, if there are duplicate icons, it renders only its last occurence. I suppose it is because of this line https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.plugins.legend/sigma.plugins.legend.js#L915, svg.icons object is indexed by icon content, which is the same and it gets overriden by following occurences of the same icon.

**Comment by Ytawo** [comment]
Fixed.

**Comment by sheymann** [comment]
ok
