### ISSUE TITLE
Adding Image to Node while doing AddNode

### ISSUE THREAD

**Issue by rainbowhat** [Linkurious/linkurious.js#377]
s.graph.addNode({
				// Main attributes:
				id: "{{$data->ads_id}}",
				label: "{{$data->title}}",
				type: 'image',
				url: 'http://www.url.com/uploads/image.jpg',
				// Display attributes:
				y: Math.random() +0.1,
				x: 1,
				size: 10,
				color: '#00f'
			});

Anyway I can do something like this?

& how do i show the label by default , on graph load ?

**Comment by sheymann** [comment]
Yes, see https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.renderers.linkurious

**Comment by rainbowhat** [comment]
@sheymann but how do i use it? with the above addNode >.<
