### ISSUE TITLE
WebGL renderer alpha support

### ISSUE THREAD

**Issue by joser93** [Linkurious/linkurious.js#378]
Greetings everyone.

In webgl plugins, the alpha colors are defined staticaly and does not use rgba values defined in JS code, here's an example of the color definition in the "sigma.webgl.edges.def.js" file: 

`'float c = a_color;',
'color.b = mod(c, 256.0); c = floor(c / 256.0);',
'color.g = mod(c, 256.0); c = floor(c / 256.0);',
'color.r = mod(c, 256.0); c = floor(c / 256.0); color /= 255.0;',
'color.a = 1.0;`

Could be an improvement in the code, to read the alpha values from the source code and keep the look and feel from other renderers. I tried to debug the code, but still can't find a nice solution for this bug, does anyone have something in mind or have tried to fix this in previous issues?

Thanks.

**Comment by sheymann** [comment]
Hi, this issue is fixed for the next major release due in September.
