### ISSUE TITLE
dragging edges

### ISSUE THREAD

**Issue by ekkis** [Linkurious/linkurious.js#380]
is there a plugin I could use for allowing the user to drag an edge from one node to another?  there is code that currently moves edges when nodes are dragged... maybe I just need to look at that but I was hoping it's already done somewhere

**Comment by sheymann** [comment]
Hi, it is done the next major release, but it will be closed source. Contact us at contact@linkurio.us to know more.

**Comment by ekkis** [comment]
does that mean you guys are discontinuing development on this project?
