### ISSUE TITLE
Parallel self-loops

### ISSUE THREAD

**Issue by cogtepsum** [Linkurious/linkurious.js#381]
I'm trying to draw a graph with several loops over some of the nodes using autoCurve. It handles non-loop parallel edges perfectly, but self-loops tend to overlap. Is there any workaround for my problem? Thank you!

**Comment by sheymann** [comment]
Hi, can you provide a screenshot and sample code to reproduce the issue? Thanks

**Comment by cogtepsum** [comment]
These are the screenshots
![full](https://cloud.githubusercontent.com/assets/10002005/17596910/3307db78-5ffc-11e6-99b6-ea9c4e801867.PNG)
![zoomed](https://cloud.githubusercontent.com/assets/10002005/17596911/3309c6a4-5ffc-11e6-88de-c5e57a98e4c9.PNG)

And I'm using this code:
```
<script>
function loadJSON(path, callback) {
  $.getJSON(path, callback);
};
loadJSON('data/short_userpath.json', function(response) {
  <!-- Create graph -->
  
    s = new sigma({
    graph: response,
    renderer: {
      container: document.getElementById('graph-container'),
      type: 'canvas'
    },
    settings: {
      doubleClickEnabled: true,
      minNodeSize: 1,
      maxNodeSize: 50,
      minEdgeSize: 1,
      maxEdgeSize: 10,
      enableEdgeHovering: true,
      edgeHoverColor: '#000',
      defaultEdgeHoverColor: '#000',
      edgeHoverSizeRatio: 1,
      edgeHoverExtremities: true,
      labelThreshold: 1,
      defaultEdgeLabelSize: 12,
      labelSizeRatio: 10,
      minArrowSize: 1,
      autoCurveSortByDirection: true,
      autoCurveRatio: 2
    }
  });
  s.settings({
    autoRescale: true});

  s.graph.nodes().forEach(function(n) {
    n.originalColor = n.color;
  });
  s.graph.edges().forEach(function(e) {
    e.originalColor = e.color;
  });

  sigma.canvas.edges.autoCurve(s);
  s.refresh();
});
</script>
```

**Comment by cogtepsum** [comment]
Sorry =) 
I'm quite new to github and JS

**Comment by cogtepsum** [comment]
And I forgot to attach my sample data
[short_userpath.txt](https://github.com/Linkurious/linkurious.js/files/413748/short_userpath.txt)

**Comment by sheymann** [comment]
Okay we've fixed this bug for the next major release. Please send an email to contact@linkurio.us for early access!

**Comment by cogtepsum** [comment]
Thanks a lot! This is great
