### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by jeangui** [Linkurious/linkurious.js#384]
Hello,

I have got a problem with the linkurious library when trying to run the "npm start".
I have got the following error message:

> _http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^
 TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ResponseStream.(anonymous function) [as setHeader] (D:\SANDBOX\DEVELOPPEMENTS\FRONTEND\LINKURIOUS\linkurious.js\node_modules\union\lib\
eam.js:88:34)
    at D:\SANDBOX\DEVELOPPEMENTS\FRONTEND\LINKURIOUS\linkurious.js\node_modules\ecstatic\lib\ecstatic\showdir.js:43:13
    at FSReqWrap.oncomplete (fs.js:123:15)" >

and this one as well:
> npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! linkurious@1.5.2 start: `http-server -p 8000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linkurious@1.5.2 start script 'http-server -p 8000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the linkurious package, >

which version of node and npm should I use ?

best regards
jeangui

**Comment by dhjnavy** [comment]
Hi Jean,
I used the following version and it works fine.
![image](https://cloud.githubusercontent.com/assets/20843939/18736580/f7651f4c-80ba-11e6-9fbd-a477b41535cb.png)

**Comment by jeangui** [comment]
Hi @dhjnavy ,

Thanks a lot for your reply.
Therefore this means that my problem is not related to node and npm version...
What could it be then ??

Any idea linkurious community ?

Best

**Comment by dhjnavy** [comment]
Hi @jeangui ,
one more point, i am using the linkurious@1.3.0, and yours is 1.5.2, i am not sure whether this is related with the problem.
the version in the package.json:
![image](https://cloud.githubusercontent.com/assets/20843939/18776475/082ee9de-819c-11e6-8da5-09b4d6b0b94b.png)

B.R
Navy

**Comment by jeangui** [comment]
Hi @dhjnavy 

thanks. I gonna test the 1.3.0 release then...

best

**Comment by sheymann** [comment]
use latest release with dependency "http-server": "~0.9.0"
