### ISSUE TITLE
failed to set the size of the node

### ISSUE THREAD

**Issue by dhjnavy** [Linkurious/linkurious.js#385]
when trying the examples, i found the value of the "size" property did not take any effect.
e.g. with the **basic.html**,
`for (i = 0; i < N; i++)`
`  g.nodes.push({`
 `   id: 'n' + i,`
`    label: 'Node ' + i,`
`    x: Math.random(),`
`    y: Math.random(),`
 `   **size: 9,**`
 `  color: '#fff'`
`  });`

If i assign one **fixed** value(here, it is 9) for the _size_ property,  the graph will always show the node with the size as 8(finally, i found the was the value of the **maxNodeSize** after debugging), and it will also assign the 8 to the **cam0:size** property and the **read_cam0:size**. It seems that the node has been shown based on the value of either **cam0:size** or **read_cam0:size** but not the **size** property. Please see the following snapshot for details.
# Snapshot with **fixed** size(9):
![baidushurufa_2016-9-22_11-35-56](https://cloud.githubusercontent.com/assets/20843939/18736341/c676e232-80b8-11e6-86cc-8593d1b56b0d.png)

furthermore, if i used the method `Math.random()` instead of the fixed value, the values for both  **cam0:size** and **read_cam0:size** will be assigned in some way I have not gotten. 
`for (i = 0; i < N; i++)`
  `  g.nodes.push({`
 `   id: 'n' + i,`
 `   label: 'Node ' + i,`
 `   x: Math.random(),`
 `   y: Math.random(),`
 `   **size: Math.random(),**`
 `   color: '#fff'`
 ` });`

please see the following snapshot for details.
# Snapshot with **random** size (Math.random()):
![image](https://cloud.githubusercontent.com/assets/20843939/18736434/85e51882-80b9-11e6-8882-4afc676dfe5e.png)

thanks in advance.
Navy

**Comment by sheymann** [comment]
call `sigmaInstance.refresh();`
