### ISSUE TITLE
Sigma GEXF import shows nothing

### ISSUE THREAD

**Issue by MartinGian** [Linkurious/linkurious.js#386]
Hi! I'm parsing a gexf string with:

`var parser = new DOMParser();`
`var gexfElement = parser.parseFromString(gexfString, "application/xml");`

and importing to the sigma instance with:

`sigma.parsers.gexf(
                    gexfElement,
                    sigmaInstance,
                    function (s) {
                        s.refresh();
                    }
                );`

but nothing shows on the page. If I inspect the graph in the callback, I can get the nodes and the edges, which means that the parse it's going well. 

I'm doing something wrong?

**Comment by sheymann** [comment]
Hi, sigma.parsers.gexf needs a URI or a DOMElement, see https://github.com/Linkurious/linkurious.js/blob/develop/plugins/sigma.parsers.gexf/sigma.parsers.gexf.js#L23

**Comment by MartinGian** [comment]
@sheymann Yeah, I show the snippet that I use in the question, but nothings happens on the UI..

**Comment by sheymann** [comment]
What is your code?

**Comment by MartinGian** [comment]
Sorry for this, close this issue, the code was in the question, but now I can solve it, I don't remember the specific problem that I had. Thanks you man.
