### ISSUE TITLE
Different output of renderer attributes

### ISSUE THREAD

**Issue by etienne-bondot** [Linkurious/linkurious.js#388]
I'm facing a magical bug for hours. I just want to use the renderer1:x and renderer1:y attributes value of two nodes to display a radial between them.

When I print the node's data :
<img width="290" alt="screen shot 2016-10-16 at 20 58 40" src="https://cloud.githubusercontent.com/assets/2827929/19420100/9ab89fca-93e4-11e6-8334-64bafd1ca257.png">

But when I print the specific values renderer1:x and renderer1:y I get
<img width="332" alt="screen shot 2016-10-16 at 20 59 57" src="https://cloud.githubusercontent.com/assets/2827929/19420103/a5aa1cd8-93e4-11e6-8b00-b60cb7141d05.png">

Here my simple code

```
console.log(sigmaInstance.graph.nodes(edge.source));
console.log('renderer1:x - ', sigmaInstance.graph.nodes(edge.source)['renderer' + conradId + ':x']);
console.log('renderer1:y - ', sigmaInstance.graph.nodes(edge.source)['renderer' + conradId + ':y']);
```

This is insane. Thanks a lot.

**Comment by ekkis** [comment]
it was a while back you asked about this.  doesn't make sense.  wondering if you ever figured it out

**Comment by etienne-bondot** [comment]
No, but we did it differently, I close this old issue.
