### ISSUE TITLE
Launch of a tooltip from a specific node

### ISSUE THREAD

**Issue by PrathyushaNarayanan** [Linkurious/linkurious.js#395]
Does linkurious.js support the launch of a tooltip from a specific node alone?

**Comment by norbertFeron** [comment]
You can open a tooltip manually on any node see the example from: 

[https://github.com/Linkurious/linkurious.js/blob/develop/examples/plugin-tooltips.html](https://github.com/Linkurious/linkurious.js/blob/develop/examples/plugin-tooltips.html)

`var tooltips = sigma.plugins.tooltips(s, ...);`
`tooltips.open(n, ...);`

Line ~260

**Comment by PrathyushaNarayanan** [comment]
@norbertFeron, Thank you for the prompt response. 

Rephrasing my question, I want to know if I can launch a tool tip on performing some user action on one node alone in the graph. 

The code I've written is as below. 

Behavior Seen : The tool tip is displayed on clicking on any node in the graph.

Required Behavior : The tool tip should be displayed only when the user clicks on the node bearing id 'node_overlap'.

-----------------------------------------------------------------------------------------------------------------
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>case transript</title>
    <style type="text/css">
        body{
            margin:auto;
            padding: 40px;
        }
        #container{
            top:0;
            bottom:0;
            left:40px;
            right:40px;
            margin: 5px;
            position: absolute;
        }
        .sigma-tooltip {
            max-width: 300px;
            max-height: 140px;
            background-color: black;
            color: white;
            font-size: 14px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.3);
            left: 52%;
            bottom: 35%;
        }
    </style>
</head>
<body>
<div id="container"></div>
<script src="../sigma.js/build/sigma.min.js"></script>
<script src="../sigma.js/src/renderers/canvas/sigma.canvas.nodes.def.js"></script>
<script src="../sigma.js/src/renderers/canvas/sigma.canvas.edges.def.js"></script>
<script src="../sigma.js/src/renderers/canvas/sigma.canvas.edgehovers.def.js"></script>
<script src="../sigma.js/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edges.tapered.js"></script>
<script src="../sigma.js/src/renderers/canvas/sigma.canvas.labels.def.js"></script>
<script src="../sigma.js/src/renderers/canvas/sigma.canvas.hovers.def.js"></script>
<script src="../sigma.js/plugins/sigma.plugins.dragNodes/sigma.plugins.dragNodes.js"></script>
<script src="../sigma.js/plugins/sigma.plugins.tooltips/sigma.plugins.tooltips.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/0.8.1/mustache.min.js"></script>
<script src="../sigma.js/plugins/sigma.renderers.linkurious/canvas/sigma.canvas.labels.def.js"></script>
<script>
    sigma.canvas.nodes.image = (function() {
        var _cache = {};
        _loading = {},
            _callbacks = {};

// Return the renderer
        var renderer = function(node, context, settings) {
            var args = arguments,
                prefix = settings('prefix') || '',
                size = node[prefix + 'size'],
                color = settings('defaultNodeColor'),
                url = node.url;

            var img = new Image();

            img.src = url;
            _cache[url] = img;


            if (_cache[url]) {
                context.save();

// Draw the clipping disc:
                context.beginPath();
                context.arc(
                    node[prefix + 'x'],
                    node[prefix + 'y'],
                    node[prefix + 'size'],
                    0,
                    Math.PI * 2,
                    true
                );
                context.closePath();
                context.clip();

// Draw the image
                context.drawImage(
                    _cache[url],
                    node[prefix + 'x'] - size,
                    node[prefix + 'y'] - size,
                    2 * size,
                    2 * size
                );

// Quit the "clipping mode":
                context.restore();

// Draw the border:
                context.beginPath();
                context.arc(
                    node[prefix + 'x'],
                    node[prefix + 'y'],
                    node[prefix + 'size'],
                    0,
                    Math.PI * 2,
                    true
                );
                context.lineWidth = 2;
                context.strokeStyle = node.color || settings('defaultNodeColor');
                context.stroke();
            } else {
                 sigma.canvas.nodes.image.cache(url);
                 sigma.canvas.nodes.def.apply(
                 sigma.canvas.nodes,
                 args
                 );
            }
        };

        // Let's add a public method to cache images, to make it possible to
// preload images before the initial rendering:
        renderer.cache = function(url, callback) {
            if (callback)
                _callbacks[url] = callback;

            if (_loading[url])
                return;

            var img = new Image();

            img.onload = function() {
                _loading[url] = false;
                _cache[url] = img;

                if (_callbacks[url]) {
                    _callbacks[url].call(this, img);
                    delete _callbacks[url];
                }
            };

            _loading[url] = true;
            img.src = url;
            _cache[url] = img;
        };

        return renderer;
    })();
    var urls = [
            'images/icon_doc-dark.svg',
            'images/icon_event-dark.svg',
            'images/icon_person-dark.svg',
            'images/icon_acc-dark.svg',
            'images/icon_act-profile.svg'
        ],
        s,
        loaded=0,
        g = {
            nodes : [],
            edges: []
        };

    g.nodes.push({
        id: 'node1',
        label: 'Narc Case #93191 Report',
        x: 3,
        y: 2.8,
        size: 30,
        type: 'image',
        url: 'images/icon_doc-dark.svg',
        color: '#216489'
    });
    g.nodes.push({
        id: 'node2',
        label: 'Narc Case #93191',
        x: 3.5,
        y: 2.6,
        size: 30,
        type: 'image',
        url: 'images/icon_event-dark.svg',
        color: '#216489'
    });
    g.nodes.push({
        id: 'node3',
        label: 'Marvin Wilson',
        x: 3.5,
        y: 3,
        size: 30,
        type: 'image',
        url: 'images/icon_person-dark.svg',
        color: '#216489'
    });
    g.nodes.push({
        id: 'node4',
        label: '5302000644',
        x: 4,
        y: 3,
        size: 30,
        type: 'image',
        url: 'images/icon_acc-dark.svg',
        color: '#216489'
    });
    g.nodes.push({
        id: 'node_overlap',
        x: 3.54,
        y: 2.97,
        size: 4,
        zIndex: 1,
        type: 'image',
        url: 'images/icon_act-profile.svg',
        color: '#216489'
    });
    g.edges.push({
        id: 'edge1',
        source: 'node1',
        target: 'node2',
        type: 'tapered',
        color:'#cccccc',
        size: 4
    });
    g.edges.push({
        id: 'edge2',
        source: 'node1',
        target: 'node3',
        type:'tapered',
        color:'#cccccc',
        size: 4
    });
    g.edges.push({
        id: 'edge3',
        source: 'node2',
        target: 'node3',
        type:'tapered',
        color:'#cccccc',
        size: 4
    });
    g.edges.push({
        id: 'edge4',
        source: 'node4',
        target: 'node3',
        type:'tapered',
        color:'#cccccc',
        size: 4
    });
    g.edges.push({
        id: 'edge5',
        source: 'node3',
        target: 'node_overlap',
        color:'#cccccc',
        size:4
    });

    urls.forEach(function(url) {
        sigma.canvas.nodes.image.cache(
            url,
            function() {
                if (++loaded === urls.length) {
                    s = new sigma({
                        container: 'container',
                        graph: g,
                        renderer: {
// IMPORTANT:
// This works only with the canvas renderer, so the
// renderer type set as "canvas" is necessary here.
                            container: document.getElementById('container'),
                            type: 'canvas'
                        },
                        settings: {
                            labelAlignment: 'bottom',
                            minNodeSize: 4,
                            maxNodeSize: 30,
                            minEdgeSize: 0.1,
                            maxEdgeSize: 4,
                            enableHovering: false,
                            maxNodeLabelLineLength: 16
                        }
                    });

                    // Instantiate the tooltips plugin with a Mustache renderer for node tooltips:
                    var config = sigma.plugins.tooltips(s, s.renderers[0], {
                        node: {
                            show: 'clickNode',
                            hide: 'clickStage',
                            cssClass: 'sigma-tooltip',
                            position: 'css',
                            //autoadjust: true,
                            template:
                            '  <div class="arrow"></div>' +
                            '  <div class="sigma-tooltip-body">' +
                            '    POI for money laundering '+
                            '  </div>',
                            renderer: function(node, template) {
                                // Returns an HTML string:
                                // return Mustache.render(template, node);

                                // Returns a DOM Element:
                                var el = document.createElement('div');
                                return el.innerHTML = Mustache.render(template, node);
                            }
                        }
                    });

                    var tooltips = sigma.plugins.tooltips(s, s.renderers[0], config);

                    // Manually open a tooltip on a node:
                   /* var n = s.graph.nodes('node5');
                    var prefix = s.renderers[0].camera.prefix;
                    tooltips.open(n, config.node, n[prefix + 'x'], n[prefix + 'y']);*/


                    tooltips.bind('shown', function(event) {
                        console.log('tooltip shown', event);
                    });

                    tooltips.bind('hidden', function(event) {
                        console.log('tooltip hidden', event);
                    });

                    // Initialize the dragNodes plugin:
                    var dragListener = sigma.plugins.dragNodes(s, s.renderers[0]);

                    dragListener.bind('startdrag', function(event) {
                        console.log(event);
                    });
                    dragListener.bind('drag', function(event) {
                        console.log(event);
                    });
                    dragListener.bind('drop', function(event) {
                        console.log(event);
                    });
                    dragListener.bind('dragend', function(event) {
                        console.log(event);
                    });

                    s.refresh();
                }
            })});
</script>

</body>
</html>

**Comment by PrathyushaNarayanan** [comment]
Can you please help identify the error in the code causing this behavior?

**Comment by norbertFeron** [comment]
If I understand, you just have to add a condition in the render function of your tooltip config to check if your node.id is equal to "node_overlap":
```
renderer: function(node, template) {
    if(node.id === "node_overlap){
        //do the Mustache render ...
    }
}
```

**Comment by PrathyushaNarayanan** [comment]
@norbertFeron, That worked just as desired. Thank you!
