### ISSUE TITLE
sigma.renderers.linkurious: icons are misaligned when hovering (WebGL)

### ISSUE THREAD

**Issue by jbilcke** [Linkurious/linkurious.js#43]
When using the customShapes plugin with the WebGL renderer, there is a small misalignment when hovering a node with a icon attached to it (this is more visible when zooming close to a node).

Sigma's core switches from WebGL to Canvas rendering when hovering node, so if the two rendering engines does not output the exact thing, it is visible during hover.

Indeed in customShapes, the WebGL renderer pre-compute a texture then scale it, while the Canvas renderer draw in realtime, so the text scale, font size, positionning.. can fluctuate with the zoom

**Comment by sheymann** [comment]
closed as fixed in next major release
