### ISSUE TITLE
sigma.renderers.linkurious: nodes have different orientations (WebGL / Canvas)

### ISSUE THREAD

**Issue by jbilcke** [Linkurious/linkurious.js#44]
The orientation is different in canvas mode VS webgl (very visible during a node hover in webgl mode, the shapes do overlap)
![before hover (pure webgl)](https://cloud.githubusercontent.com/assets/136294/5193281/95f2d3bc-74ff-11e4-945f-c78beac1efef.png)
![during hover (canvas shape is not aligned on webgl shape)](https://cloud.githubusercontent.com/assets/136294/5193283/981cc4c2-74ff-11e4-9813-f0e2da859fde.png)

**Comment by sheymann** [comment]
closed as fixed in next major release
