### ISSUE TITLE
sigma.renderers.linkurious: add support for cutting shapes into images (Canvas)

### ISSUE THREAD

**Issue by jbilcke** [Linkurious/linkurious.js#45]
The Canvas renderer of the customShapes plugin cannot display custom shapes (eg. star) together with images (in a node's background).

Since the WebGL version can do this kind of image shaping it would be nice to have the Canvas renderer do the same (here is an example, left is canvas and right is webgl):

![shapes and images](https://cloud.githubusercontent.com/assets/136294/5193370/88e82b08-7500-11e4-83ac-b925d031d29b.png)

**Comment by sheymann** [comment]
closed as fixed in next major release
