### ISSUE TITLE
sigma.renderers.linkurious: improve the star shape (WebGL)

### ISSUE THREAD

**Issue by jbilcke** [Linkurious/linkurious.js#47]
That's a minor issue, but stars are rendered using a different math function in Canvas and WebGL modes, and the actual WebGL version cannot for instance tune the "innerRadius" of stars

however there is a work-in-progress version of the star algorithm (commented in the GLSL part of the customShapes source) which needs to be finished and tested

**Comment by sheymann** [comment]
closed as fixed in next major release
