### ISSUE TITLE
sigma.renderers.linkurious: improve hover labelling (WebGL / Canvas)

### ISSUE THREAD

**Issue by jbilcke** [Linkurious/linkurious.js#49]
I was in a hurry so I just added an option to make the label "float" outside, without touching to the shape of the label:

![node label](https://cloud.githubusercontent.com/assets/136294/5193320/f8c79f0e-74ff-11e4-8c94-c8d293990971.png)

Maybe it would be better to have both sides straight

**Comment by jbilcke** [comment]
some additional material:

maybe look into https://github.com/jacomyal/sigma.js/pull/468

**Comment by sheymann** [comment]
closed as fixed in next major release
