### ISSUE TITLE
sigma.renderers.linkurious: add support for borders (WebGL)

### ISSUE THREAD

**Issue by jbilcke** [Linkurious/linkurious.js#50]
The WebGL renderer (right on this screenshot) does not implement borders:

![screen shot 2014-12-22 at 09 10 08](https://cloud.githubusercontent.com/assets/136294/5522551/b83ef214-89ba-11e4-9b55-749a1e634a34.png)

Although not a critical issue, this is actually an oversight since the Canvas can do it, so it is better to fix this.

For most shapes this should be easy, by playing with the "radius" parameter (ie. change the color depending on the position of a point to the center), for others where the radius is not directly expressed in the drawing function, this will be a bit more tricky

**Comment by ekkis** [comment]
was this ever implemented? I need that functionality now

**Comment by sheymann** [comment]
The ticket is open so it is not implemented.

**Comment by sheymann** [comment]
closed as done in next major release
