### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#55]
- [ ] Home with content of http://linkurio.us/toolkit/
- [ ] Intro
- [x] Examples (with editable code)
- [ ] Tutorials
- [ ] API reference (streamlined and generated from source comments)
- [x] Plugins (readmes + API)
- [ ] Download (+[Customize](http://getbootstrap.com/customize/) to generate custom builds)
- [ ] Help
- [ ] Studio (e.g. http://live.amcharts.com/)

**Comment by Flo-Schield-Bobby** [comment]
What do you think of Docstrap ?
https://github.com/terryweiss/docstrap

**Comment by sheymann** [comment]
@Flo-Schield-Bobby yes something like this + plugin README files. Docstrap looks nice not not sure about maintenance, see https://github.com/terryweiss/docstrap/issues/75

**Comment by Flo-Schield-Bobby** [comment]
Yeah I saw it unfortunately, however I already used it for a project and it's a very good base ;
If it supports bootstrap 3 soon, it could be enough for our needs.

**Comment by sheymann** [comment]
Sure, I also need to think about how to integrate html examples and to improve them: I'd like to have a "playground" where the code can be edited live à la JSbin, and a user interface to easily tweak sigma and plugins settings.

**Comment by sheymann** [comment]
Replace the wiki with a website where we can add interactive demos of the features and tutorials. Like http://maurizzzio.github.io/greuler/

**Comment by sheymann** [comment]
inspiration:
- http://leafletjs.com
- https://vida.io/documents/45ASDxtvF2RzaeC4P

**Comment by sheymann** [comment]
Demo services:
- [jsFiddle](http://jsfiddle.net/FloSchieldBobby/wu38t08d/)
- http://jsbin.com/?html,js,output

**Comment by mdamien** [comment]
I think we should write the API doc by hand, it's gonna force to have a small public API (and we can start with one already documented in the wiki)

**Comment by sheymann** [comment]
It would generate maintenance issues because the developer would need to update both the jsdoc and the external doc. Why can't we generate the doc from source?

**Comment by mdamien** [comment]
I think that's two separate things/ideas:

* A doc documenting all the code auto-generated but not easy to read
* A nice public API documentation like https://github.com/Linkurious/linkurious.js/wiki/Public-API

For example, for Leaflet, [they abandoned the idea to autogenerate the public API](https://github.com/Leaflet/Leaflet/issues/815#issuecomment-7113379).

In short, it forces us to make a nice, concise and simple public API

**Comment by sheymann** [comment]
it makes sense

**Comment by mdamien** [comment]
Idea to bootstrap this: Generate a table of the settings and the plugin settings

**Comment by mdamien** [comment]
Our comments aren't really jsdoc ready and the enclosing `function` of each file makes jsdoc not parse them. An easier and faster solution would be to do our own parser.

**Comment by mdamien** [comment]
Found someone else who did his own parser and it's working well with our code: https://github.com/jsdoc2md/jsdoc-parse

**Comment by mdamien** [comment]
Ok the issues today are:

* the documentation is all over the wiki + README + comments + examples
* not easy to get started

For me, the solution could be:

* have a gallery of examples easy to navigate, like bl.ocks.org
    * cool to get started and discover what you can do with lk.js
* have the README be more oriented towards giving directions (wiki for public API, examples, ..)

Here's a solution to each things to fix:

* Home with content of http://linkurio.us/toolkit/ => Marketing page, let's let it be at lk.us/toolkit
* Intro => README + getting started as an example
* Examples (with editable code) => A gallery of examples (powered by gist eventually)
* Tutorials =>  Examples (like `bl.ocks.org`)
* API reference (streamlined and generated from source comments)
   * internal doc: need to re-organize the code or do my own parsing and publish on `gh-pages` or `docs/`
   * public API: Already documented in the wiki
* Plugins => README with plugin list (readmes + API)
* Download => README
* Help  => README
* Studio  => as an example ?

So, gonna first try to have a better README pointing towards the already existing docs

**Comment by mdamien** [comment]
Current work:

* [ ] examples gallery linking to JSFiddles
* [ ] plugins gallery linking to their subdirectory

**Comment by sheymann** [comment]
We should use github pages instead of rawgit. Examples/plugins won't be updated if files are modified in the repo because rawgit put them in cache.

**Comment by mdamien** [comment]
The cache is for a "short time", see [FAQ](https://rawgit.com/faq):

> RawGit acts as a caching proxy, forwarding requests to GitHub, caching the responses either for a short time (in the case of rawgit.com URLs) or permanently (in the case of cdn.rawgit.com URLs), and relaying them to your browser with the correct Content-Type headers.

The problem with having it on `gh-pages` is to synchronize the two branches (maybe at each release for example, like `stable`)

**Comment by mdamien** [comment]
Ok, so now that we have two nice pages, what could be improved ?

**examples:**
- categories (plugins, core, use-cases)

**plugins**
- categories
- small search
- page preload

But there is a risk to over-engineer this.

**Comment by sheymann** [comment]
+ use favicon and colors of Linkurious: #f65565 (pink), #1e1e32 (purple)

**Comment by sheymann** [comment]
Another very good example gallery: https://zoomcharts.com/en/gallery/

with editable example, e.g.: https://zoomcharts.com/developers/en/net-chart/examples/filters/highlight-path.html

**Comment by sheymann** [comment]
fixed for [Ogma](https://linkurio.us/ogma-js-library-large-scale-graph-visualization/).
