### ISSUE TITLE
Add onDestroy parameter to the tooltip API

### ISSUE THREAD

**Issue by callicles** [Linkurious/linkurious.js#70]
We have a renderer method that is called for processing the tooltip template but we do not have anything to clean it up properly on destroy.

This will be useful for clean angular integration.

**Comment by sheymann** [comment]
will be named onRemove for consistency with the JS DOM API.

**Comment by sheymann** [comment]
It may not be necessary, just listen to the `hidden` event:

```js
tooltips.bind('hidden', function(event) {
  console.log('tooltip hidden', event);
});
```

**Comment by callicles** [comment]
thanks, not necessary after all.
