### ISSUE TITLE
SVG fragment as node image

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#82]
Node images support bitmap formats only (png, jpg,...). How can we support vectorial format (svg)?

**Comment by jbilcke** [comment]
Maybe there is a (clean) way:

https://gist.github.com/Caged/4649511

 "This works OK if the SVG's styles are inline. The SVG element must contain an xmlns attribute. Webkit also requires you specify a font size on `text` elements."

```
var svg  = document.getElementById('graph'),
    xml  = new XMLSerializer().serializeToString(svg),
    data = "data:image/svg+xml;base64," + btoa(xml),
    img  = new Image()
 
img.setAttribute('src', data)
document.body.appendChild(img)
```

**Comment by jbilcke** [comment]
There are other solutions on this page, in the "SVG to Canvas" section:

http://svgopen.org/2010/papers/62-From_SVG_to_Canvas_and_Back/#svg_to_canvas

**Comment by sheymann** [comment]
fixed for [Ogma](https://linkurio.us/ogma-js-library-large-scale-graph-visualization/).
