### ISSUE TITLE
Use Bitmap fonts for fast text rendering?

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#83]
Text rendering is a costly operation. A traditional technique in game development is to generate [Bitmap fonts](http://www.wikiwand.com/en/Computer_font#/Bitmap_fonts) with fixed sizes. They are extremely fast to render but also very bad at scaling. Bitmap fonts may thus be suitable with the Sigma setting `labelSize` equal to `fixed`.

TODO:
- [ ] measure cost of rendering node/edge labels, time taken in function of the number of elements.
- [ ] edit the canvas renderers for labels to support Bitmap fonts with no external dependency.
- [ ] measure the cost of rendering node/edge labels with a Bitmap font. [Anonymous Pro](http://www.marksimonson.com/fonts/view/anonymous-pro) is shipped with [bitmaps for small sizes](http://www.marksimonson.com/info/anonymous-pro-usage-notes).
- [ ] if the cost difference is not significant, abandon this idea.
- [ ] if necessary, generate good Bitmap fonts based on existing fonts such as [Roboto](http://www.google.com/fonts/specimen/Roboto), using tools such as [BMFont](http://www.angelcode.com/products/bmfont/), [Glyphite](https://www.glyphite.com/), [Littera](http://kvazars.com/littera/), or [Shoebox](http://renderhjs.net/shoebox/bitmapFont.htm).

**Comment by jbilcke** [comment]
We can try distance field fonts, at least for the WebGL version:

"A distance field is generated from a high resolution image, and then stored into a channel of a lower-resolution texture"

https://github.com/libgdx/libgdx/wiki/Distance-field-fonts
http://www.valvesoftware.com/publications/2007/SIGGRAPH2007_AlphaTestedMagnification.pdf

this could potentially be used for Canvas as well:

"In the simplest case, this texture can then be rendered simply by using the alphatesting and alpha-thresholding feature of modern GPUs, without a custom shader."

This may be achieved by working with Canvas pixel processing functions:
http://www.html5rocks.com/en/tutorials/canvas/imagefilters/?redirect_from_locale=fr

This kind of canvas rendering is computationally expensive, but maybe we do not need to compute fonts in real-time. Rendering could be async / lazy, recomputed only if the user zoom, made in a webworker..
The test implementation should thus have some benchmarks to determine the best settings.

**Comment by mdamien** [comment]
Some first insights about optimizing text rendering: http://stackoverflow.com/questions/31321815/

Also, I started a branch to work on [optimizing edges labels rendering](https://github.com/Linkurious/linkurious.js/tree/bench/edge-labels/bench): It looks like font rendering isn't the main bottleneck when rendering labels, it's more things like context switching and `save()`/`restore()`.

**Comment by mdamien** [comment]
Looking into other renderers:

In the very popular Phaser renderer, they use filltext directly: [Text.js#L501](https://github.com/photonstorm/phaser/blob/858ad5161028d45d65679c88fc1e9a08ceed1f8f/src/gameobjects/Text.js#L501)

But they do other optims:

* approximate measureText via some heuristic [Text.js#L1124-L1125](https://github.com/photonstorm/phaser/blob/858ad5161028d45d65679c88fc1e9a08ceed1f8f/src/gameobjects/Text.js#L1124-L1125)
* dirty checking [Text.js#L1233](https://github.com/photonstorm/phaser/blob/858ad5161028d45d65679c88fc1e9a08ceed1f8f/src/gameobjects/Text.js#L1233)

**Comment by sheymann** [comment]
Caching is indeed suggested: http://stackoverflow.com/questions/31321815/optimize-text-rendering-in-the-canvas-the-rendering-speed-of-truetype-versus-b#comment50664958_31324598

**Comment by sheymann** [comment]
closed as non constructive anymore
