### ISSUE TITLE
use throw new Error('msg') instead of throw 'msg'

### ISSUE THREAD

**Issue by callicles** [Linkurious/linkurious.js#91]
Now the errors are thrown as:

```js
throw 'some error'
```

We should use:
```ja
throw new Error('some error');
```

Stack trace will be correct

- [x] sigma.exporters.spreadsheet
- [x] sigma.exporters.xlsx
- [x] sigma.helpers.graph
- [x] sigma.layout.forceAtlas2
- [x] sigma.plugins.activeState
- [x] sigma.plugins.design
- [x] sigma.plugins.edgeSiblings
- [x] sigma.plugins.filter
- [x] sigma.plugins.locate
- [x] sigma.plugins.tooltips
- [x] sigma.renderers.edgeLabels
- [x] sigma.renderers.halo
- [x] sigma.statistics.louvain

**Comment by sheymann** [comment]
Use case:

```js
try {
    throw new Error('myError');
}
catch(e) {
    alert(e.stack);
}
```

Notice that Error.prototype.stack is non-standard and is not on a standards track.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack

Basic support is available on Chrome, Firefox (Gecko), Internet Explorer, Opera, Safari with various implementations.

**Comment by sheymann** [comment]
Core changes: PR submitted https://github.com/jacomyal/sigma.js/pull/536

**Comment by sheymann** [comment]
@callicles plugins are now updated, you can checkout the branch linkurious-version.

**Comment by callicles** [comment]
thanks

**Comment by sheymann** [comment]
done, created #96 to follow the sigma PR https://github.com/jacomyal/sigma.js/pull/536
