### ISSUE TITLE
The fastest open source graph drawing engine?

### ISSUE THREAD

**Issue by anvaka** [Linkurious/linkurious.js#93]
Hi guys,

I read this in the readme file:

> Linkurious.js provides a collection of HTML5 features based on Sigma.js, the fastest open source Javascript graph drawing engine on the market

I'm curious, do you have data to support this statement?

**Comment by anvaka** [comment]
Hi guys, could you please take a look :)? 

Please feel free to contribute to [perf suite](https://github.com/anvaka/graph-drawing-libraries/tree/master/src/src/scripts/examples/jacomyal_sigma.js/02.perf) to prove the statement. 

Last time I checked sigma wasn't the fastest, but maybe I did it wrong: https://www.youtube.com/watch?v=Ax7KSQZ0_hk . If so I'd like to fix the error.

**Comment by sheymann** [comment]
Hey @anvaka, welcome here! What do you want to test exactly? Here it seems that you're testing one layout.

For us performance is a tradeoff between rendering speed and flexibility of possible user interactions. I like VivaGraph a lot, but no Canvas renderer is a no go in corporate environment where a large number of workstations don't have graphic cards.

I've started to write a performance guide for Sigma/Linkurious.js here: https://github.com/Linkurious/linkurious.js/wiki/Performance

The [ForceAtlas2](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.layout.forceAtlas2) layout can also be tweaked for fast computation (`barnesHutOptimize`, `iterationsPerRender ` or `background` mode)

cheers

**Comment by anvaka** [comment]
Thanks for the answer!

You mentioned "The fastest graph drawing engine", so I'd love to see a demo, that shows Sigma's drawing being the fastest. 

I'm not trying to convince people to use VivaGraph. It's just in my demos VivaGraph runs faster than Sigma. Compare: [VivaGraph](http://anvaka.github.io/graph-drawing-libraries/performance/?lib=anvaka%2FVivaGraphJS&graph=grid3&n=20&m=20&k=20) vs [Sigma](http://anvaka.github.io/graph-drawing-libraries/performance/?lib=jacomyal%2Fsigma.js&graph=grid3&n=20&m=20&k=20) .

If you are saying that sigma is the fastest, I'd like to update my demos too, to not skew the information.

I made a jsbin, which uses latest sigma (1.0.3) and latest force atlas. Please feel free to update it to make rendering as fast as possible: http://jsbin.com/kapafejama/4/edit?html,js

I will port it back to my comparison.

**Comment by anvaka** [comment]
cc @jacomyal and @Yomguithereal - I'd appreciate your feedback too. I honestly believe you've made a great library, guys. And if I'm wrong showing that sigma.js is slower in this particular example - I need to fix it.

**Comment by jacomyal** [comment]
@anvaka :
 - I have nothing to do with the statement you're refering to here.
 - I have nothing to do with linkurious.js and its team, and I'd like to keep it that way.

**Comment by anvaka** [comment]
@jacomyal understood, no worries. I'm all for making graph drawing on the web faster, regardless of which library does it. We should keep pushing the limits.

**Comment by sheymann** [comment]
@anvaka here is some improvements: http://jsbin.com/jarimewove/2/ but I need the [Linkurious.js version of the ForceAtlas](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.layout.forceAtlas2) layout to make it really faster.

**Comment by Yomguithereal** [comment]
@sheymann: why would the Linkurious' version of ForceAtlas2 be faster since it is the same as sigma's one (an outdated one, what's more) but with a misleading autostop option?

**Comment by sheymann** [comment]
@Yomguithereal Rendering is very costly so I want to avoid it as long as possible. Our version has a `maxIterations` option (different from the `autoStop` option) to stop the layout after X iterations, thus allowing to render the graph at the end of the layout only. This approach provides dramatic speed up in practice, and I can even add a smooth interpolation of node coordinates at the end.

**Comment by anvaka** [comment]
@sheymann Thank you for modifications. I did side by side rendering of the 3d grid with your version and latest sigma. Here is unedited and unlisted recording side by side: https://www.youtube.com/watch?v=sMzn6Ki6T6o

I'm using latest version of Chrome `43.0.2357.65 (64-bit)`, on regular mac book pro 13", OSX 10.9.5. I do not see any visible difference. Do you see different results?

**Comment by sheymann** [comment]
statement fixed in http://linkurio.us/toolkit/
