### ISSUE TITLE
sigma.layouts.fruchtermanReingold

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious.js#94]
Implement the Fruchterman-Reingold layout algorithm.

Code can be adapted from https://gist.github.com/sheymann/5057611

**Comment by sheymann** [comment]
@callicles need review https://github.com/Linkurious/linkurious.js/tree/plugin/fruchterman/plugins/sigma.layout.fruchtermanReingold

**Comment by callicles** [comment]
pull request ?

**Comment by sheymann** [comment]
@callicles https://github.com/Linkurious/linkurious.js/pull/95

**Comment by sheymann** [comment]
done
