### ISSUE TITLE
Lasso does not select after doubleClickStage

### ISSUE THREAD

**Issue by apitts** [Linkurious/linkurious.js#99]
I believe this is related to this issue: 
https://github.com/jacomyal/sigma.js/issues/565

Essentially the lasso won't work after double clicking the stage (specifically the line does not appear until mouse release and after mouse release the tool does not select).

**Comment by sheymann** [comment]
We use a different plugin to drag nodes, so this issue may be related to the Sigma core itself. Can you provide a working code to reproduce the bug please?

Thanks Andrew.

**Comment by apitts** [comment]
I agree with you @sheymann, it's very likely that it is an issue in sigma core that only presents itself on the drag and lasso plugins (note: it's present in both the linkurious.js and sigma.js drag plugins). Perhaps we should close this issue and just leave the issue in sigma.js.

I'm afraid I can't really post code to reproduce the issue as it's a user interaction issue. It's present though in both the example files in the repo - the drag example and the lasso example.  To see it, just double click on the stage and then try to drag a node or lasso a node respectively.

**Comment by sheymann** [comment]
Okay let's open an issue on Sigma repo and keep this one open with a link to it.

**Comment by sheymann** [comment]
rel: https://github.com/jacomyal/sigma.js/issues/565

**Comment by apitts** [comment]
OK - cool.  I won't open a new issue unless you think appropriate as the one already referenced above should cover it. I will just add a clarifying comment to that issue.

**Comment by sheymann** [comment]
Perfect. Usually it helps the developers when you give the exact steps to reproduce, e.g.:

1. open xx.html example
- double-click on stage
- click + hold on a node
- etc.

**Comment by sheymann** [comment]
@apitts I've made important improvements to the dragNodes plugin, please check it out! I'm not able to reproduce your issue.

**Comment by apitts** [comment]
Thanks @sheymann! I just tried to reproduce the issue on the linkurious demo and was not able to (I definitely saw it in the example files previously though). For the moment I've removed double clicking the stage from my application and parked the issue. I'll close this issue and reply if I learn anything else.
